"use client";

import { useEffect } from "react";
import type { CSSProperties } from "react";
import { useSearchParams } from "next/navigation";
import { AlertCircle, ArrowLeft, CalendarClock, ChevronRight, EyeOff, ShieldCheck } from "lucide-react";
import FixtureBottomNav from "../_components/FixtureBottomNav";

type Variant = "a" | "b" | "c";
type State = "fresh" | "normal" | "caution" | "error" | "hidden";
type Mode = "light" | "dark";
const variantKeys: Variant[] = ["a", "b", "c"];
const stateKeys: State[] = ["fresh", "normal", "caution", "error", "hidden"];
const stateLabels: Record<State, string> = { fresh: "Fresh payday", normal: "Normal", caution: "Caution", error: "Connection error", hidden: "Balance hidden" };
const variants: Record<Variant, { name: string; summary: string }> = {
  a: { name: "Reading line", summary: "A single, quiet reading line from the available money to what needs attention." },
  b: { name: "Today board", summary: "A practical desktop split: orientation holds steady while the next action sits beside it." },
  c: { name: "Rhythm", summary: "A time-led home where the pay-period rhythm makes the next useful moment obvious." },
};
const stateCopy: Record<State, { amount: string; status: string; reading: string; next: string; detail: string }> = {
  fresh: { amount: "£842", status: "On track", reading: "Your pay has landed. Your bills and planned moves are already covered.", next: "Set aside £140 for the dentist", detail: "12 days until payday" },
  normal: { amount: "£428", status: "On track", reading: "You are on pace for this pay period.", next: "Nothing needs you today", detail: "8 days until payday" },
  caution: { amount: "£116", status: "Tight", reading: "Your room is getting tight after the weekend.", next: "Check the £70 card repayment", detail: "8 days until payday" },
  error: { amount: "Not available", status: "Could not check", reading: "Your accounts may still be visible, but we cannot safely calculate what is free until payday.", next: "Your latest figure could not be checked", detail: "Try again after your accounts refresh" },
  hidden: { amount: "£••••", status: "On track", reading: "Your plan is still on pace.", next: "Nothing needs you today", detail: "8 days until payday" },
};

function Money({ children }: { children: string }) { return <span className="font-mono tabular-nums">{children}</span>; }

function PreviewControls({ variant, state, mode, query }: { variant: Variant; state: State; mode: Mode; query: (next: Partial<{variant: Variant; state: State; mode: Mode}>) => string }) {
  return <nav aria-label="G88 design preview controls" className="fixed inset-x-0 bottom-0 z-[80] border-t border-white/10 bg-slate-950/95 px-3 py-2 text-white shadow-xl lg:left-64" style={{ paddingBottom: "max(8px, env(safe-area-inset-bottom, 0px))" }}><div className="mx-auto flex w-full max-w-6xl items-center gap-1.5">{variantKeys.map(key => <a key={key} href={query({variant:key})} aria-label={`Variant ${key.toUpperCase()}: ${variants[key].name}`} title={variants[key].name} aria-current={key === variant ? "page" : undefined} className={`inline-flex min-h-11 min-w-11 shrink-0 touch-manipulation items-center justify-center rounded-xl px-3 text-[12px] font-semibold transition-colors [-webkit-tap-highlight-color:transparent] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 active:scale-95 motion-reduce:transition-none ${key === variant ? "bg-white text-slate-950" : "text-slate-300 hover:bg-white/10"}`}>{key.toUpperCase()}</a>)}<label className="ml-auto flex min-h-11 min-w-0 items-center rounded-xl bg-white/10 px-2.5 text-[12px] text-slate-300 focus-within:ring-2 focus-within:ring-indigo-400"><span className="sr-only">Preview Home state</span><select name="preview-state" value={state} onChange={event => window.location.assign(query({state:event.target.value as State}))} className="min-w-0 cursor-pointer bg-slate-800 pr-1 font-semibold text-white outline-none">{stateKeys.map(key => <option key={key} value={key} className="bg-slate-900">{stateLabels[key]}</option>)}</select></label><a href={query({mode: mode === "dark" ? "light" : "dark"})} className="inline-flex min-h-11 shrink-0 touch-manipulation items-center rounded-xl px-3 text-[12px] font-semibold text-slate-300 transition-colors [-webkit-tap-highlight-color:transparent] hover:bg-white/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-400 active:scale-95 motion-reduce:transition-none">{mode === "dark" ? "Light" : "Dark"}</a></div></nav>;
}

export default function G88HomeCanvasClient() {
  const params = useSearchParams();
  const requestedVariant = params.get("variant");
  const variant: Variant = requestedVariant === "b" || requestedVariant === "c" ? requestedVariant : "a";
  const state: State = ["fresh", "normal", "caution", "error", "hidden"].includes(params.get("state") ?? "") ? params.get("state") as State : "normal";
  const mode: Mode = params.get("mode") === "dark" ? "dark" : "light";
  const copy = stateCopy[state];
  useEffect(() => { document.documentElement.classList.toggle("dark", mode === "dark"); }, [mode]);
  const query = (next: Partial<{variant: Variant; state: State; mode: Mode}>) => `?variant=${next.variant ?? variant}&state=${next.state ?? state}&mode=${next.mode ?? mode}`;
  const risk = state === "caution"; const problem = state === "error";
  const safeHero = (
    <section aria-labelledby="safe-heading" className="glass-hero rounded-3xl p-5 shadow-sm sm:p-7">
      <div className="flex items-start justify-between gap-4"><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500 dark:text-slate-400">Safe to Spend</p><h2 id="safe-heading" className="mt-2 text-[13px] font-medium text-slate-600 dark:text-slate-300">Available after bills and plans</h2></div>{state === "hidden" ? <EyeOff size={19} className="text-slate-500 dark:text-slate-400" aria-label="Balance hidden" /> : <ShieldCheck size={20} className="text-slate-500 dark:text-slate-400" aria-hidden="true" />}</div>
      <p className={`mt-5 inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${risk ? "bg-slate-100 text-amber-800 dark:bg-slate-700/70 dark:text-amber-200" : problem ? "bg-slate-100 text-slate-700 dark:bg-slate-700/70 dark:text-slate-200" : "bg-emerald-50 text-emerald-700 dark:bg-emerald-400/10 dark:text-emerald-300"}`}>{copy.status}</p>
      {problem ? <p className="mt-4 text-base font-bold text-slate-900 dark:text-slate-100">Your Safe to Spend figure is unavailable</p> : <p className="mt-3 text-[40px] font-bold leading-none tracking-[-0.04em] text-slate-900 dark:text-slate-100"><Money>{copy.amount}</Money></p>}
      <p className="mt-4 max-w-[55ch] text-[14px] leading-6 text-slate-600 dark:text-slate-300">{copy.reading}</p>
      <a href={problem ? query({ state: "normal" }) : "#next"} className="mt-5 inline-flex min-h-11 items-center gap-1 rounded-xl px-3 text-sm font-semibold text-indigo-600 transition hover:bg-indigo-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 active:scale-95 dark:text-indigo-400 dark:hover:bg-indigo-500/10">{problem ? "Try again" : "See how we got here"}<ChevronRight size={16} aria-hidden="true" /></a>
    </section>
  );
  const next = <section id="next" aria-labelledby="next-heading" className="border-t border-slate-200 pt-5 dark:border-slate-700"><div className="flex items-start gap-3"><span className={`mt-1.5 h-2 w-2 rounded-full ${risk ? "bg-amber-500" : problem ? "bg-slate-400" : "bg-emerald-500"}`} /><div className="min-w-0"><h2 id="next-heading" className="text-base font-bold text-slate-950 dark:text-white">{copy.next}</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-400">{copy.detail}</p></div></div>{risk && <a href="/cards" className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold text-slate-800 transition hover:bg-slate-100 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 active:scale-95 dark:border-slate-700 dark:text-slate-100 dark:hover:bg-slate-800"><CalendarClock size={16} aria-hidden="true"/>Review it</a>}</section>;
  const evidence = <section aria-labelledby="evidence-heading" className="border-t border-slate-200 pt-5 dark:border-slate-700"><div className="flex items-center justify-between"><h2 id="evidence-heading" className="text-base font-bold text-slate-950 dark:text-white">This pay period</h2><a href="/spend" className="inline-flex min-h-11 items-center text-sm font-semibold text-indigo-600 hover:text-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-indigo-300">View spend</a></div><dl className="mt-4 grid grid-cols-3 gap-3"><div><dt className="text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-600 dark:text-slate-400">In</dt><dd className="mt-1 text-sm font-bold text-slate-950 dark:text-white"><Money>{state === "hidden" ? "£••••" : "£2,640"}</Money></dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-600 dark:text-slate-400">Out</dt><dd className="mt-1 text-sm font-bold text-slate-950 dark:text-white"><Money>{state === "hidden" ? "£••••" : "£1,904"}</Money></dd></div><div><dt className="text-[10px] font-semibold uppercase tracking-[0.07em] text-slate-600 dark:text-slate-400">Moved</dt><dd className="mt-1 text-sm font-bold text-slate-950 dark:text-white"><Money>{state === "hidden" ? "£••••" : "£308"}</Money></dd></div></dl></section>;
  return <main className={`${mode === "dark" ? "dark" : ""} min-h-dvh bg-[#f0f2f7] text-slate-900 selection:bg-indigo-200 dark:bg-[#0f172a] dark:text-slate-100`} style={{ colorScheme: mode, "--design-controls-clearance": "76px" } as CSSProperties}><a href="#content" className="sr-only focus:not-sr-only focus:absolute focus:left-4 focus:top-4 focus:z-[100] focus:rounded-xl focus:bg-slate-950 focus:px-4 focus:py-3 focus:text-white">Skip to preview</a><div className="mx-auto max-w-6xl px-4 pb-60 pt-6 sm:px-6 sm:pt-10 lg:pb-24"><header className="mb-8"><a href="/design" className="inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-slate-600 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={16} aria-hidden="true"/> Design rounds</a><h1 className="mt-4 text-balance text-[30px] font-bold tracking-[-0.04em] text-slate-950 dark:text-white">Home, on the canvas</h1><p className="mt-2 max-w-[65ch] text-sm leading-6 text-slate-600 dark:text-slate-400">{variants[variant].summary} Preview only, with static fixture data.</p></header><div id="content" className={variant === "b" ? "grid gap-8 lg:grid-cols-[minmax(0,1fr)_minmax(320px,.8fr)]" : "mx-auto max-w-2xl space-y-8"}>{variant === "c" && <p className="text-sm font-medium text-slate-600 dark:text-slate-400">{state === "error" ? "Monday, 15 September" : `Monday, 15 September · ${copy.detail}`}</p>}<div className="space-y-8">{safeHero}{variant === "a" && next}{evidence}</div><div className={variant === "b" ? "space-y-8 lg:border-l lg:border-slate-200 lg:pl-8 dark:lg:border-slate-700" : "space-y-8"}>{variant !== "a" && next}<section className="border-t border-slate-200 pt-5 dark:border-slate-700"><h2 className="text-base font-bold text-slate-950 dark:text-white">A quieter brief</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">No other changes need your attention. We will keep watching the bills and planned moves already in place.</p>{state === "fresh" && <p className="mt-4 text-sm font-semibold text-emerald-700 dark:text-emerald-300">Your first planned move is ready to set aside.</p>}{risk && <p className="mt-4 flex gap-2 text-sm leading-6 text-slate-700 dark:text-slate-300"><AlertCircle size={17} className="mt-0.5 shrink-0 text-amber-500" aria-hidden="true"/>The card repayment has not been confirmed.</p>}</section></div></div></div><FixtureBottomNav active="Home"/><PreviewControls variant={variant} state={state} mode={mode} query={query}/></main>;
}
