/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        brand: "#b91c1c",
        "brand-dark": "#991b1b",
        primary: "#4f46e5",
        "primary-deep": "#7c3aed",
        canvas: "#f0f2f7",
        "canvas-dark": "#0f172a",
        surface: "#ffffff",
        "surface-dark": "#1e293b",
        border: "#f1f5f9",
        "border-dark": "#334155",
        ink: "#0f172a",
        "ink-dark": "#f1f5f9",
        muted: "#94a3b8",
        "muted-deep": "#64748b",
        success: "#10b981",
        warning: "#f59e0b",
        danger: "#ef4444",
        "cat-groceries": "#34d399",
        "cat-eating-out": "#fb923c",
        "cat-transport": "#60a5fa",
        "cat-entertainment": "#c084fc",
        "cat-shopping": "#f472b6",
        "cat-bills": "#fb7185",
        "cat-subscriptions": "#22d3ee",
        "cat-health": "#2dd4bf",
        "cat-beauty": "#e879f9",
        "cat-travel": "#818cf8",
        "cat-software": "#a3e635",
        "cat-savings": "#fbbf24",
        "cat-debt": "#f87171",
        "cat-transfer": "#cbd5e1",
        "cat-income": "#4ade80",
        "cat-cash": "#facc15",
        "cat-charity": "#f9a8d4",
        "cat-other": "#94a3b8",
      },
      borderRadius: {
        chip: 8,
        control: 12,
        card: 16,
        hero: 24,
      },
      fontSize: {
        display:  ["30px", { lineHeight: "36px", fontWeight: "700" }],
        headline: ["20px", { lineHeight: "26px", fontWeight: "700" }],
        title:    ["14px", { lineHeight: "20px", fontWeight: "600" }],
        body:     ["14px", { lineHeight: "21px", fontWeight: "400" }],
        label:    ["11px", { lineHeight: "14px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
