"use client";

import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, ChevronRight, CircleAlert } from "lucide-react";

type Variant = "a" | "b" | "c";
type State = "ahead" | "steady" | "short" | "empty" | "loading" | "error";
const variants: Variant[] = ["a", "b", "c"];
const readings = {
  ahead: { in: 3240, out: 2016, moved: 938, end: 286, verdict: "£286 ahead", cause: "You spent less than usual and moved £180 into your buffer." },
  steady: { in: 3240, out: 2022, moved: 1218, end: 0, verdict: "On track this month", cause: "Bills, spending and planned moves settled where expected." },
  short: { in: 3240, out: 2176, moved: 1138, end: -74, verdict: "£74 over your usual month", cause: "Eating out ran warmer, while everything else stayed close to plan." },
} as const;
const money = (value: number) => `${value < 0 ? "−" : ""}£${Math.abs(value).toLocaleString("en-GB")}`;

function Reconciliation({ state }: { state: keyof typeof readings }) {
  const item = readings[state]; const closes = [142, 196, 238, item.end];
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none" aria-labelledby="reconciled-title"><h2 id="reconciled-title" className="text-base font-bold">The reconciled month</h2><div className="mt-4 grid grid-cols-2 gap-4 text-sm sm:grid-cols-4">{[["In", item.in], ["Out", item.out], ["Moved", item.moved], ["End position", item.end]].map(([label, value]) => <div key={label as string}><p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">{label}</p><p className="mt-1 font-mono font-bold tabular-nums">{money(value as number)}</p></div>)}</div><p className="mt-4 border-t border-slate-200 pt-3 font-mono text-sm font-bold tabular-nums dark:border-slate-700">{money(item.in)} − {money(item.out)} − {money(item.moved)} = {money(item.end)}</p>{item.end < 0 ? <p className="mt-5 border-t border-slate-200 pt-4 text-sm leading-6 text-slate-600 dark:border-slate-700 dark:text-slate-400">The month closed below the usual position at <span className="font-mono font-bold text-red-700 dark:text-red-300">{money(item.end)}</span>. A comparison chart is withheld here so a shortfall is not drawn as an upward gain.</p> : <figure className="mt-5 border-t border-slate-200 pt-4 dark:border-slate-700"><figcaption className="text-sm font-semibold">End position across four closed periods</figcaption><div className="mt-3 grid grid-cols-4 gap-3" role="img" aria-label={`End position was £142 in June, £196 in July, £238 in August and ${money(item.end)} in September.`}>{closes.map((value, index) => <div key={index}><div className="flex h-24 items-end rounded-lg bg-slate-100 p-1 dark:bg-slate-700"><div className="w-full rounded-md bg-indigo-500" style={{ height: `${Math.max(10, Math.min(100, Math.abs(value) / 3))}%` }} /></div><p className="mt-2 font-mono text-xs font-semibold tabular-nums">{money(value)}</p><p className="text-xs text-slate-500 dark:text-slate-400">{["Jun", "Jul", "Aug", "Sep"][index]}</p></div>)}</div></figure>}</section>;
}

export default function Client() {
  const params = useSearchParams(); const raw = params.get("variant"); const variant: Variant = variants.includes(raw as Variant) ? raw as Variant : "a"; const candidate = params.get("state") as State; const state: State = (["ahead", "steady", "short", "empty", "loading", "error"] as State[]).includes(candidate) ? candidate : "steady"; const dark = params.get("mode") === "dark";
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]); const href = (next: Partial<{ variant: Variant; state: State; mode: string }>) => `?variant=${next.variant ?? variant}&state=${next.state ?? state}&mode=${next.mode ?? (dark ? "dark" : "light")}`;
  let body: React.ReactNode;
  if (state === "loading") body = <div aria-label="Loading monthly reading" className="space-y-4"><div className="h-24 animate-pulse rounded-2xl bg-slate-200 motion-reduce:animate-none dark:bg-slate-800" /><div className="h-52 animate-pulse rounded-2xl bg-slate-200 motion-reduce:animate-none dark:bg-slate-800" /></div>;
  else if (state === "empty") body = <section className="max-w-2xl"><h2 className="text-xl font-bold">Your month is still taking shape</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">There is not enough history for a fair comparison yet. Return once this period has settled.</p><a href="/accounts" className="mt-4 inline-flex min-h-11 items-center text-sm font-semibold text-indigo-700 dark:text-indigo-300">Check your accounts <ChevronRight size={16} /></a></section>;
  else if (state === "error") body = <section className="max-w-2xl"><h2 className="flex items-center gap-2 text-xl font-bold"><CircleAlert size={20} />Couldn’t build this month’s reading</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">Your accounts remain available. Try again after your next refresh.</p><a href="/accounts" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Check your accounts</a></section>;
  else { const item = readings[state]; const verdict = <section><h2 className="text-balance text-[28px] font-bold tracking-tight">{item.verdict}</h2><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-400">{item.cause}</p><p className="mt-4 border-y border-slate-300 py-4 text-sm leading-6 text-slate-600 dark:border-slate-700 dark:text-slate-400">Income arrived, then bills, everyday spending and planned moves took their place. The reconciliation closes what is left.</p><a href={state === "short" ? "/transactions" : "/month/story"} className="mt-4 inline-flex min-h-11 items-center gap-1 rounded-xl border border-slate-200 px-3 text-sm font-semibold dark:border-slate-700">{state === "short" ? "Review eating out" : "Play the month story"}<ChevronRight size={16} /></a></section>; const evidence = <Reconciliation state={state} />; const sequence = <section className="mx-auto max-w-2xl"><h2 className="text-2xl font-bold">How September settled</h2><div className="mt-6 space-y-5 border-l border-slate-300 pl-5 dark:border-slate-700"><div><p className="font-semibold">Payday brought in {money(item.in)}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Income set the month in motion.</p></div><div><p className="font-semibold">Everyday life took {money(item.out)}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">{item.cause}</p></div><div><p className="font-semibold">You moved {money(item.moved)}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Planned money stayed distinct from spending.</p></div><div><p className="font-semibold">The month closed at {money(item.end)}</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Now see the arithmetic underneath.</p></div></div><a href="/month/story" className="mt-6 inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-indigo-700 dark:text-indigo-300">Play the month story <ChevronRight size={16} /></a></section>; body = variant === "b" ? <div className="grid gap-8 lg:grid-cols-[1fr_20rem]"><div className="lg:sticky lg:top-6 lg:self-start">{verdict}</div>{evidence}</div> : variant === "c" ? <div className="space-y-10">{verdict}{sequence}{evidence}</div> : <div className="mx-auto max-w-2xl space-y-8">{verdict}{evidence}</div>; }
  return <main className="min-h-dvh bg-[#f0f2f7] text-slate-900 dark:bg-[#0f172a] dark:text-slate-100"><a href="#month" className="sr-only focus:not-sr-only">Skip to month</a><div id="month" className="mx-auto max-w-5xl px-4 pb-32 pt-6"><a href="/design" className="inline-flex min-h-11 items-center gap-1 text-sm text-slate-600 dark:text-slate-400"><ArrowLeft size={16} />Design rounds</a><h1 className="mt-5 text-[30px] font-bold tracking-tight">September, explained</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">A month-close verdict, its cause, then the evidence.</p><div className="mt-10">{body}</div></div><nav aria-label="Preview controls" className="fixed bottom-3 left-1/2 z-20 flex max-w-[calc(100vw-24px)] -translate-x-1/2 gap-1 overflow-x-auto rounded-2xl bg-slate-950 p-1.5">{variants.map(value => <a key={value} href={href({ variant: value })} className="grid min-h-11 min-w-11 place-items-center rounded-xl px-2 text-xs font-semibold text-white">{value.toUpperCase()}</a>)}{(["ahead", "steady", "short", "empty", "loading", "error"] as State[]).map(value => <a key={value} href={href({ state: value })} className="inline-flex min-h-11 items-center rounded-xl px-2 text-xs font-semibold text-white">{value}</a>)}<a href={href({ mode: dark ? "light" : "dark" })} className="inline-flex min-h-11 items-center rounded-xl px-2 text-xs font-semibold text-white">{dark ? "Light" : "Dark"}</a></nav></main>;
}
