"use client";
import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Bell, CreditCard, Database, HelpCircle, KeyRound, LogOut, Moon, ShieldCheck, UserRound } from "lucide-react";
import SettingsGroupSection from "@/app/settings/SettingsGroupSection";
import SettingsCard from "@/app/settings/SettingsCard";
import { SettingsHelpCard, SettingsSecurityCard, SettingsTutorialsCard } from "@/app/settings/SettingsSupportCards";
import { SETTINGS_GROUP_ORDER, type SettingsGroup } from "@/app/settings/settingsGroupOrder";

type Variant = "a" | "b" | "c"; type Mode = "light" | "dark"; type State = "ready" | "attention" | "empty";
const variants: Variant[] = ["a", "b", "c"];
const notes: Record<Variant, { title: string; thesis: string; tradeoff: string }> = {
  a: { title: "A · Guided settings", thesis: "Canvas orientation names the few things people come here to change, then related controls appear in one dependable reading order.", tradeoff: "The clearest long-page route, though it remains a scroll." },
  b: { title: "B · Settings rail", thesis: "Desktop keeps a plain canvas map of settings in view while each bounded control group sits in a work column.", tradeoff: "Fast on a wide screen, with little added value on a phone." },
  c: { title: "C · Intent groups", thesis: "Controls are ordered by why you would use them: account access, security and connections, behaviour, then data and help.", tradeoff: "More task-led, but less like the established live order." },
};
const groups = [
  { ...SETTINGS_GROUP_ORDER[0], Icon: UserRound, rows: [["Profile", "Alex Morgan"], ["Sign-in methods", "Google & Apple"], ["Your plan", "Standard · £5.99/month"]] },
  { ...SETTINGS_GROUP_ORDER[2], Icon: Moon, rows: [["Display", "Dark mode on"], ["Penny", "Can set things up with confirmation"], ["Notifications", "Bills & payday reminders"]] },
  { ...SETTINGS_GROUP_ORDER[1], Icon: ShieldCheck, rows: [["App lock", "Face ID on"], ["Where money can come from", "8 connected accounts"], ["Connected assistants", "None connected"]] },
  { ...SETTINGS_GROUP_ORDER[3], Icon: Database, rows: [["Your data", "Export or delete"], ["How Sorted works", "Replay the tour"], ["Help", "Get support"]] },
];
function Group({ group, attention }: { group: typeof groups[number]; attention: boolean }) { return <SettingsCard>{group.rows.map(([name, detail], i) => <div key={name} className="flex min-h-[68px] items-center gap-3 border-b border-slate-100 px-4 py-3 last:border-b-0 dark:border-slate-700"><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="text-sm font-semibold text-slate-900 dark:text-slate-100">{name}</span>{attention && group.id === "how-sorted-behaves" && i === 2 && <span className="size-1.5 rounded-full bg-amber-500" aria-label="Needs attention" />}</span><span className="mt-0.5 block truncate text-xs text-slate-600 dark:text-slate-400">{attention && group.id === "how-sorted-behaves" && i === 2 ? "Notifications need permission" : detail}</span></span></div>)}</SettingsCard>; }
function Groups({ variant, state }: { variant: Variant; state: State }) { if (state === "empty") return <div className="space-y-9"><div className="max-w-[65ch] border-y border-slate-300/80 py-6 dark:border-slate-700"><h2 className="text-xl font-bold text-slate-900 dark:text-slate-100">Finish setting up when you are ready</h2><p className="mt-2 text-pretty text-sm leading-6 text-slate-600 dark:text-slate-400">Connect a bank to personalise permissions and preferences. You can still manage your sign-in and privacy choices.</p></div><SettingsGroupSection group="account-access">{null}</SettingsGroupSection><SettingsGroupSection group="security-connected"><SettingsSecurityCard enabled onChange={() => {}} /></SettingsGroupSection><SettingsGroupSection group="data-help"><SettingsTutorialsCard flows={[{ id: "overview", label: "Getting around Sorted", blurb: "Replay the product tour" }]} onStart={() => {}} /><SettingsHelpCard onTerms={() => {}} onPrivacy={() => {}} /></SettingsGroupSection></div>; const order = variant === "c" ? [groups[0], groups[2], groups[1], groups[3]] : groups; const list = <div className="space-y-9">{order.map((group) => <SettingsGroupSection key={group.id} group={group.id as SettingsGroup}><Group group={group} attention={state === "attention"} /></SettingsGroupSection>)}<SettingsGroupSection group="leave-delete"><SettingsCard><div className="flex flex-wrap gap-3 p-4"><span className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700 dark:border-slate-600 dark:text-slate-200"><LogOut size={16} aria-hidden="true" />Sign out</span><span className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-red-200 px-4 text-sm font-semibold text-red-700 dark:border-red-400/30 dark:text-red-300"><Database size={16} aria-hidden="true" />Delete account & data</span></div></SettingsCard></SettingsGroupSection></div>; if (variant !== "b") return list; return <div className="lg:grid lg:grid-cols-[minmax(0,.7fr)_minmax(0,1.3fr)] lg:gap-10"><nav aria-label="Settings sections" className="mb-8 flex flex-wrap gap-x-4 gap-y-2 lg:sticky lg:top-6 lg:mb-0 lg:flex-col lg:items-start"><p className="w-full text-sm font-semibold text-slate-900 dark:text-slate-100">Jump to</p>{groups.map((group) => <a key={group.id} href={`#${group.id}`} className="rounded text-sm font-semibold text-indigo-700 hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-indigo-300">{group.title}</a>)}</nav><div className="border-t border-slate-300/80 pt-8 dark:border-slate-700 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0">{list}</div></div>; }
function Switcher({ variant, state, mode }: { variant: Variant; state: State; mode: Mode }) { return <nav aria-label="Preview controls" className="mx-auto mt-5 w-full max-w-6xl border-t border-slate-300/80 px-4 pt-4 sm:px-6 dark:border-slate-700"><div className="flex flex-wrap gap-2"><div className="flex flex-wrap items-center gap-1 rounded-xl bg-slate-900 p-1 shadow-sm dark:border dark:border-slate-700">{variants.map((v) => <a key={v} href={`?variant=${v}&state=${state}&mode=${mode}`} className={`flex min-h-11 items-center rounded-lg px-3 text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white ${v === variant ? "bg-indigo-600 text-white" : "text-slate-300 hover:text-white"}`}>{v.toUpperCase()}</a>)}</div><div className="flex flex-wrap items-center gap-1 rounded-xl border border-slate-300 bg-white p-1 shadow-sm dark:border-slate-700 dark:bg-slate-800">{(["ready", "attention", "empty"] as State[]).map((s) => <a key={s} href={`?variant=${variant}&state=${s}&mode=${mode}`} className={`flex min-h-11 items-center rounded-lg px-3 text-xs font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 ${s === state ? "bg-slate-100 text-slate-950 dark:bg-slate-700 dark:text-white" : "text-slate-600 hover:text-slate-950 dark:text-slate-300 dark:hover:text-white"}`}>{s === "ready" ? "Ready" : s === "attention" ? "Alert" : "Empty"}</a>)}<a href={`?variant=${variant}&state=${state}&mode=${mode === "dark" ? "light" : "dark"}`} className="flex min-h-11 items-center rounded-lg px-3 text-xs font-semibold text-slate-600 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-slate-300 dark:hover:text-white">{mode === "dark" ? "Light" : "Dark"}</a></div></div></nav>; }
export default function G94SettingsCanvasClient() { const params = useSearchParams(); const raw = params.get("variant"); const variant: Variant = variants.includes(raw as Variant) ? raw as Variant : "a"; const state: State = params.get("state") === "attention" ? "attention" : params.get("state") === "empty" ? "empty" : "ready"; const mode: Mode = params.get("mode") === "dark" ? "dark" : "light"; useEffect(() => { document.documentElement.classList.toggle("dark", mode === "dark"); document.querySelector('meta[name="color-scheme"]')?.setAttribute("content", mode); }, [mode]); const note = notes[variant]; return <div className={mode === "dark" ? "dark" : ""}><div className="min-h-dvh overflow-x-hidden bg-[#f0f2f7] pb-32 dark:bg-[#0f172a]"><a href="#main" className="sr-only fixed left-4 top-3 z-[60] rounded-lg bg-white px-3 py-2 text-sm font-semibold text-indigo-700 focus:not-sr-only focus:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:bg-slate-800 dark:text-indigo-300">Skip to settings</a><main id="main" className="mx-auto w-full max-w-6xl px-4 pb-10 pt-[calc(env(safe-area-inset-top)+1.5rem)] sm:px-6"><a href="/design" className="inline-flex min-h-11 items-center gap-1.5 rounded-xl px-1 text-sm font-medium text-slate-600 hover:text-slate-950 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={17} aria-hidden="true" />Back to design</a><header className="mt-4 border-b border-slate-300/80 pb-6 dark:border-slate-700"><h1 className="text-balance text-[30px] font-bold leading-[1.08] tracking-[-0.035em] text-slate-950 dark:text-white">Settings, without the profile hero</h1><p className="mt-2 max-w-[65ch] text-pretty text-sm leading-6 text-slate-600 dark:text-slate-400">G94 Canvas Before Cards round. The canvas explains where to go. Bounded groups carry controls, permissions and destructive actions.</p><div className="mt-4 max-w-[65ch] border-l border-indigo-300 pl-3 dark:border-indigo-500"><p className="text-sm font-semibold text-slate-900 dark:text-slate-100">{note.title}</p><p className="mt-1 text-sm leading-5 text-slate-600 dark:text-slate-400">{note.thesis}</p><p className="mt-1 text-xs text-slate-600 dark:text-slate-400">Trade-off: {note.tradeoff}</p></div></header><div className="mt-8"><Groups variant={variant} state={state} /></div><p className="mt-10 flex items-center gap-2 border-t border-slate-300/80 pt-5 text-xs text-slate-600 dark:border-slate-700 dark:text-slate-400"><HelpCircle size={15} aria-hidden="true" />Static preview only. No preferences or permissions change here.</p></main><Switcher variant={variant} state={state} mode={mode} /></div></div>; }
