#!/usr/bin/env bash
#
# build-board-web-assets.sh — populate the Board flavour's own copy of the
# bundled web export (H66).
#
# The Board app must open directly on /ops/go-live instead of Home. Rather
# than bake in a live server.url (which would break the "works from bundled
# assets talking to the API" contract every other build in this project
# relies on, per Kevin's brief), this script copies the SAME static export
# Sorted already ships (capacitor-spike/www — built by
# frontend/scripts/build-mobile.sh, same UAT API base) into the Board
# flavour's own asset overlay (android/app/src/board/assets/public/), then
# replaces ONLY that copy's index.html with a tiny redirect shim to
# /ops/go-live.html (the exact static file Next's export emits for that
# route — see the comment in the redirect HTML below for why the .html
# suffix is deliberate, and why the extensionless path is NOT an
# alternative). capacitor-spike/www itself, and Sorted's real
# src/main/assets/public/ (populated by `npx cap sync android`), are never
# touched.
#
# Bundling the whole export for Board (rather than trimming it down to
# just the ops pages) is deliberate for this first version — see H66.
#
# Also derives a Board-scoped android/app/src/board/assets/capacitor.config.json
# override from the real capacitor.config.json via jq (overriding only
# appId/appName), rather than a hand-maintained copy that would silently
# drift from any future plugin/server config changes to the real file. So
# native Capacitor.getPlatform()/App plugin calls made from ops pages
# describe the Board app correctly, not Sorted. This is a flavour asset
# overlay, exactly like the res/ overlay apply-board-icons.sh writes:
# Gradle merges assets/ by relative path with flavour taking priority over
# main, so this file is used only for Board variants; Sorted's own
# src/main/assets/capacitor.config.json (regenerated by `npx cap sync
# android`) is untouched.
#
# Also writes a freshness stamp (src/board/.www-stamp, review finding
# P2/FIX4, 2026-09-17) recording a content hash of the www/ export this
# copy was made from. `npx cap sync android` only refreshes Sorted's
# src/main/assets/public/, never Board's src/board/assets/ overlay, so the
# ordinary "edit frontend, rebuild www, cap sync, gradlew" loop leaves
# Board's copy silently stale with no signal — the stamp is what lets
# app/build.gradle's verifyBoardWebAssets task (wired into every Board
# variant's preBuild) catch that and fail loudly instead. The stamp lives
# directly under src/board/, NOT inside src/board/assets/, so it is never
# itself bundled into the APK (Gradle only picks up recognised source-set
# subdirectories like assets/, res/, java/ — a stray file directly under
# src/board/ is invisible to the Android build).
#
# Run from capacitor-spike/, AFTER capacitor-spike/www has been built
# (frontend/scripts/build-mobile.sh) and copied into place (see
# ANDROID_PUSH.md step 4). Idempotent: safe to re-run any time, including
# after `npx cap add android` wipes android/ (src/board/ is a
# Capacitor-agnostic overlay dir `cap add android` doesn't know about, so
# it needs the same re-apply step as the icons).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SPIKE_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

WWW_DIR="$SPIKE_DIR/www"
BOARD_DIR="$SPIKE_DIR/android/app/src/board"
BOARD_ASSETS_DIR="$BOARD_DIR/assets"
BOARD_PUBLIC_DIR="$BOARD_ASSETS_DIR/public"
BOARD_STAMP="$BOARD_DIR/.www-stamp"

# Must match apply-board-flavor.sh's BOARD_APPLICATION_ID.
BOARD_APPLICATION_ID="co.uk.auriqltd.sorted.board"

if [[ ! -d "$SPIKE_DIR/android" ]]; then
  echo "Android project not present — skipping Board web assets (run npx cap add android first)"
  exit 0
fi

if [[ ! -d "$WWW_DIR" ]] || [[ -z "$(ls -A "$WWW_DIR" 2>/dev/null)" ]]; then
  echo "ERROR: $WWW_DIR is missing or empty. Build the export first:" >&2
  echo "  cd frontend && npm run build:mobile && rm -rf ../capacitor-spike/www/* && cp -r out/* ../capacitor-spike/www/" >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "ERROR: jq not found on PATH (needed to derive capacitor.config.json)" >&2
  exit 1
fi

echo "Source export: $WWW_DIR"
echo "Board assets:  $BOARD_PUBLIC_DIR"
echo

rm -rf "$BOARD_PUBLIC_DIR"
mkdir -p "$BOARD_PUBLIC_DIR"
cp -r "$WWW_DIR/." "$BOARD_PUBLIC_DIR/"
echo "copied $(find "$BOARD_PUBLIC_DIR" -type f | wc -l) files from $WWW_DIR"

# Overwrite ONLY this copy's index.html with a redirect shim. The target is
# the exact file Next's static export emits for /ops/go-live
# (capacitor-spike/www/ops/go-live.html — confirmed present, no trailing
# slash / no nested index.html, since this project's next.config.ts does
# not set trailingSlash). The extensionless "/ops/go-live" path is NOT an
# alternative, and is actively dangerous here: Capacitor's
# WebViewLocalServer runs in html5mode by default (Board does not disable
# it), which means any extensionless path that doesn't match a real file
# falls back to serving index.html — which IS this very redirect shim.
# Targeting the extensionless path would therefore have the shim redirect
# to itself, an infinite reload loop on every launch. The literal
# `.html` file is a real, distinct asset, so it has no such fallback and
# is the only safe target.
cat > "$BOARD_PUBLIC_DIR/index.html" <<'HTMLEOF'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<meta http-equiv="refresh" content="0; url=/ops/go-live.html" />
<title>Board</title>
<script>window.location.replace('/ops/go-live.html');</script>
</head>
<body></body>
</html>
HTMLEOF
echo "wrote $BOARD_PUBLIC_DIR/index.html (redirect shim -> /ops/go-live.html)"

mkdir -p "$BOARD_ASSETS_DIR"
jq --arg appId "$BOARD_APPLICATION_ID" --arg appName "Board" \
  '.appId = $appId | .appName = $appName' \
  "$SPIKE_DIR/capacitor.config.json" > "$BOARD_ASSETS_DIR/capacitor.config.json"
echo "wrote $BOARD_ASSETS_DIR/capacitor.config.json (derived from capacitor.config.json via jq: appId/appName overridden, everything else — plugins, server block — carried through unchanged)"

# Freshness stamp: order-independent content hash (sort before hashing, so
# file rename/reorder noise doesn't matter, only actual content changes
# do) of every file under the source export this copy was made from.
WWW_HASH="$(find "$WWW_DIR" -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum | awk '{print $1}')"
echo "$WWW_HASH" > "$BOARD_STAMP"
echo "wrote $BOARD_STAMP ($WWW_HASH)"

echo
echo "Done. Board flavour web assets written under src/board/assets/ (src/main/assets/public/ untouched)."
