"use client";

import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, ArrowUpRight, CreditCard, Info, TrendingDown } from "lucide-react";
import { CARD_META, DRIVERS, OUTLOOK_CARDS, PER_CARD } from "@/app/design/cards-page/fixtures";

type Variant = "a" | "b" | "c";
type Mode = "light" | "dark";
type State = "growing" | "reducing" | "empty";
const variants: Variant[] = ["a", "b", "c"];

const copy: Record<Variant, { title: string; thesis: string; tradeoff: string }> = {
  a: { title: "A · Reconciled position", thesis: "The canvas leads with the total debt, cycle movement and exact arithmetic. Card accounts become a compact evidence register below.", tradeoff: "Most direct on a phone, though the forecast stays intentionally quiet." },
  b: { title: "B · Trajectory rail", thesis: "The canvas holds the debt position on a sticky desktop rail while every card and its projection remains a bounded work object alongside it.", tradeoff: "Strongest wide-screen comparison, with a more deliberate desktop split." },
  c: { title: "C · Drivers first", thesis: "The same canvas position is followed by the movement drivers before the card accounts, so the next useful lever is visible before the account inventory.", tradeoff: "Best for explaining why the total moved, but less suited to users who came straight to a specific card." },
};

function money(value: number) { return `£${Math.abs(value).toLocaleString("en-GB")}`; }
function nameFor(id: string) { return CARD_META.find((card) => card.accountId === id)?.cleanName ?? "Card account"; }

function Position({ state }: { state: State }) {
  if (state === "empty") return <div className="max-w-[65ch]"><h2 className="text-balance text-xl font-bold text-slate-950 dark:text-white">No carried card balance</h2><p className="mt-2 text-pretty text-sm leading-6 text-slate-600 dark:text-slate-400">Your card accounts are clearing in full this cycle. When a balance carries, its position and projection will appear here.</p></div>;
  const reducing = state === "reducing";
  const delta = reducing ? 625 : 1_205;
  const spend = reducing ? 490 : 1_325;
  const payments = reducing ? 1_115 : 120;
  return <div className="max-w-[65ch]"><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500 dark:text-slate-400">Card position</p><div className="mt-2 flex flex-wrap items-baseline gap-x-3 gap-y-1"><h2 className="font-mono text-[34px] font-bold leading-none tracking-[-0.035em] tabular-nums text-slate-950 dark:text-white">£24,954 owed</h2><span className={`inline-flex items-center gap-1 text-sm font-semibold ${reducing ? "text-emerald-700 dark:text-emerald-400" : "text-slate-700 dark:text-slate-200"}`}>{reducing ? <TrendingDown size={16} aria-hidden="true" /> : <ArrowUpRight size={16} aria-hidden="true" />}{reducing ? "£625 lower this cycle" : "£1,205 higher this cycle"}</span></div><p className="mt-3 text-pretty text-sm leading-6 text-slate-600 dark:text-slate-400">{reducing ? "Payments overtook new card spending. Keep that pace and the carried balances would clear by Jun 2027." : "Your position grew this cycle. The figures below show how new spending, payments and each card add back to that movement."}</p><div className="mt-5 border-y border-slate-300/80 py-3 dark:border-slate-700"><p className="font-mono text-[15px] font-semibold tabular-nums text-slate-900 dark:text-slate-100">{money(spend)} new spend − {money(payments)} payments = {reducing ? "−" : "+"}{money(delta)} movement</p><p className="mt-1 text-xs text-slate-600 dark:text-slate-400">Every movement figure reconciles to the cycle change above.</p></div></div>;
}

function Drivers() { return <section aria-labelledby="drivers-title" className="scroll-mt-6"><div className="px-1"><h2 id="drivers-title" className="text-base font-bold text-slate-900 dark:text-slate-100">What drove the movement</h2><p className="mt-1 max-w-[65ch] text-pretty text-[13px] leading-5 text-slate-600 dark:text-slate-400">Card spending rose most in shopping, entertainment and groceries. These are drivers, not another card surface.</p></div><div className="mt-3 grid grid-cols-2 gap-x-5 gap-y-3 border-y border-slate-300/80 py-4 dark:border-slate-700 sm:grid-cols-5">{DRIVERS.map((driver) => <div key={driver.category}><p className="font-mono text-sm font-bold tabular-nums text-slate-900 dark:text-slate-100">{money(driver.total)}</p><p className="mt-0.5 text-xs text-slate-600 dark:text-slate-400">{driver.category}</p></div>)}</div></section>; }

function Accounts() { return <section aria-labelledby="accounts-title" className="scroll-mt-6"><div className="px-1"><h2 id="accounts-title" className="text-base font-bold text-slate-900 dark:text-slate-100">Card accounts & projections</h2><p className="mt-1 max-w-[65ch] text-pretty text-[13px] leading-5 text-slate-600 dark:text-slate-400">Each account earns its own boundary because its balance, rate and projected clear date form one actionable object.</p></div><div className="mt-3 space-y-3">{OUTLOOK_CARDS.map((outlook) => { const card = PER_CARD.find((row) => row.account_id === outlook.accountId); return <article key={outlook.accountId} className="rounded-2xl border border-slate-200/80 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className="flex size-9 shrink-0 items-center justify-center rounded-xl bg-rose-50 text-rose-500 dark:bg-rose-400/10 dark:text-rose-300"><CreditCard size={17} aria-hidden="true" /></span><h3 className="truncate text-sm font-bold text-slate-900 dark:text-slate-100">{nameFor(outlook.accountId)}</h3></div><p className="mt-3 text-xs text-slate-600 dark:text-slate-400">{outlook.payingInterest ? "Interest charged now" : outlook.ratePill.label}</p></div><div className="shrink-0 text-right"><p className="font-mono text-lg font-bold tabular-nums text-slate-900 dark:text-slate-100">{money(card?.balance ?? 0)}</p><p className="mt-0.5 text-xs text-slate-600 dark:text-slate-400">owed</p></div></div><div className="mt-4 grid grid-cols-2 gap-3 border-t border-slate-200/80 pt-3 dark:border-slate-700"><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500 dark:text-slate-400">This cycle</p><p className="mt-1 font-mono text-sm font-semibold tabular-nums text-slate-900 dark:text-slate-100">{card && card.delta >= 0 ? "+" : "−"}{money(card?.delta ?? 0)}</p></div><div><p className="text-[11px] font-semibold uppercase tracking-[0.08em] text-slate-500 dark:text-slate-400">At this pace</p><p className="mt-1 text-sm font-semibold text-slate-900 dark:text-slate-100">{outlook.payoffMonth ? `Clears ${new Intl.DateTimeFormat("en-GB", { month: "short", year: "numeric" }).format(new Date(`${outlook.payoffMonth}-01T00:00:00`))}` : "Clears monthly"}</p></div></div></article>; })}</div></section>; }

function Content({ variant, state }: { variant: Variant; state: State }) { if (state === "empty") return <div className="mt-8"><Position state={state} /></div>; const position = <Position state={state} />; const accounts = <Accounts />; const drivers = <Drivers />; if (variant === "a") return <div className="space-y-9">{position}{accounts}{drivers}</div>; if (variant === "c") return <div className="space-y-9">{position}{drivers}{accounts}</div>; return <div className="lg:grid lg:grid-cols-[minmax(0,.8fr)_minmax(0,1.2fr)] lg:gap-10"><div className="lg:sticky lg:top-6 lg:self-start">{position}<nav className="mt-6 flex gap-4 text-sm font-semibold text-indigo-700 dark:text-indigo-300"><a href="#accounts-title" className="rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Accounts</a><a href="#drivers-title" className="rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Drivers</a></nav></div><div className="mt-9 border-t border-slate-300/80 pt-8 dark:border-slate-700 lg:mt-0 lg:border-l lg:border-t-0 lg:pl-10 lg:pt-0"><div className="space-y-9">{accounts}{drivers}</div></div></div>; }

function Switcher({ variant, state, mode }: { variant: Variant; state: State; mode: Mode }) { return <div className="fixed inset-x-0 bottom-[calc(env(safe-area-inset-bottom)+14px)] z-50 flex justify-center px-3"><div className="flex max-w-full items-center gap-1 overflow-x-auto rounded-full border border-white/15 bg-slate-900/95 p-1 shadow-xl">{variants.map((item) => <a key={item} href={`?variant=${item}&state=${state}&mode=${mode}`} className={`flex min-h-11 shrink-0 items-center rounded-full px-3 text-xs font-semibold transition-colors active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white ${item === variant ? "bg-indigo-600 text-white" : "text-slate-300 hover:text-white"}`}>{item.toUpperCase()}</a>)}<span className="h-5 w-px bg-white/20" aria-hidden="true" />{(["growing", "reducing", "empty"] as State[]).map((item) => <a key={item} aria-label={item === "growing" ? "Balance growing state" : item === "reducing" ? "Balance reducing state" : "No carried balance state"} href={`?variant=${variant}&state=${item}&mode=${mode}`} className={`flex min-h-11 shrink-0 items-center rounded-full px-3 text-xs font-semibold transition-colors active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white ${item === state ? "bg-slate-700 text-white" : "text-slate-300 hover:text-white"}`}>{item === "growing" ? "Up" : item === "reducing" ? "Down" : "Clear"}</a>)}<a href={`?variant=${variant}&state=${state}&mode=${mode === "dark" ? "light" : "dark"}`} className="flex min-h-11 shrink-0 items-center rounded-full px-3 text-xs font-semibold text-slate-300 hover:text-white active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white">{mode === "dark" ? "Light" : "Dark"}</a></div></div>; }

export default function G91CardsCanvasClient() { const params = useSearchParams(); const raw = params.get("variant"); const variant: Variant = variants.includes(raw as Variant) ? raw as Variant : "a"; const state: State = params.get("state") === "reducing" ? "reducing" : params.get("state") === "empty" ? "empty" : "growing"; const mode: Mode = params.get("mode") === "dark" ? "dark" : "light"; useEffect(() => { document.documentElement.classList.toggle("dark", mode === "dark"); document.querySelector('meta[name="color-scheme"]')?.setAttribute("content", mode); }, [mode]); const note = copy[variant]; return <div className={mode === "dark" ? "dark" : ""}><div className="min-h-dvh overflow-x-hidden bg-[#f0f2f7] pb-32 dark:bg-[#0f172a]"><a href="#main" className="sr-only fixed left-4 top-3 z-[60] rounded-lg bg-white px-3 py-2 text-sm font-semibold text-indigo-700 shadow-sm focus:not-sr-only focus:outline-none focus:ring-2 focus:ring-indigo-500 dark:bg-slate-800 dark:text-indigo-300">Skip to cards</a><main id="main" className="mx-auto w-full max-w-6xl px-4 pb-10 pt-[calc(env(safe-area-inset-top)+1.5rem)] sm:px-6"><a href="/design" className="inline-flex min-h-11 items-center gap-1.5 rounded-xl px-1 text-[13px] font-medium text-slate-600 hover:text-slate-950 active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-slate-400 dark:hover:text-white"><ArrowLeft size={17} aria-hidden="true" />Back to design</a><header className="mt-4 border-b border-slate-300/80 pb-6 dark:border-slate-700"><h1 className="text-balance text-[30px] font-bold leading-[1.08] tracking-[-0.035em] text-slate-950 dark:text-white">Cards, with the position in view</h1><p className="mt-2 max-w-[65ch] text-pretty text-sm leading-6 text-slate-600 dark:text-slate-400">G91 Canvas Before Cards round. Debt position, movement and reconciliation stay on the canvas. Each account and its projection remains a bounded object.</p><div className="mt-4 max-w-[65ch] border-l border-indigo-300 pl-3 dark:border-indigo-500"><p className="text-sm font-semibold text-slate-800 dark:text-slate-200">{note.title}</p><p className="mt-1 text-pretty text-sm leading-5 text-slate-600 dark:text-slate-400">{note.thesis}</p><p className="mt-1 text-xs text-slate-500 dark:text-slate-500">Trade-off: {note.tradeoff}</p></div></header><div className="mt-8"><Content variant={variant} state={state} /></div><p className="mt-10 flex items-start gap-2 border-t border-slate-300/80 pt-5 text-xs leading-5 text-slate-600 dark:border-slate-700 dark:text-slate-400"><Info size={15} className="mt-0.5 shrink-0" aria-hidden="true" />Illustrative figures only. A projection describes the current pace, not a promise.</p></main><Switcher variant={variant} state={state} mode={mode} /></div></div>; }
