"use client";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, ArrowLeft, ChevronDown, CreditCard } from "lucide-react";
type V="a"|"b"|"c"; type S="growing"|"reducing"|"empty";
const cards=[['Halifax Clarity','£3,420','24.9% APR','Interest charged now'],['Barclaycard','£8,210','0% until May 2027','£320 lower this cycle'],['Amex Gold','£13,324','Clears monthly','£115 higher this cycle']];
const q=(v:V,s:S,d:boolean)=>`?variant=${v}&state=${s}&mode=${d?'dark':'light'}`;
function Switch({v,s,d}:{v:V;s:S;d:boolean}){return <nav aria-label="Preview controls" className="fixed inset-x-0 bottom-3 z-50 flex justify-center px-2"><div className="flex max-w-full overflow-x-auto rounded-2xl bg-slate-900/95 p-1 text-xs shadow-xl">{(['a','b','c']as V[]).map(x=><a key={x} href={q(x,s,d)} className={`min-h-11 shrink-0 rounded-xl px-3 py-3 font-semibold ${x===v?'bg-indigo-600 text-white':'text-slate-200'}`}>{x.toUpperCase()}</a>)}{(['growing','reducing','empty']as S[]).map(x=><a key={x} href={q(v,x,d)} className="min-h-11 shrink-0 px-2 py-3 text-slate-200">{x}</a>)}<a href={q(v,s,!d)} className="min-h-11 shrink-0 px-2 py-3 text-slate-200">{d?'light':'dark'}</a></div></nav>}
function Position({s}:{s:S}){if(s==='empty')return <section><h2 className="text-xl font-bold">No carried card balance</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Your card accounts are clearing in full this cycle.</p></section>;const reducing=s==='reducing', spend=reducing?490:1325,pay=reducing?1115:120,opening=reducing?25579:23749;return <section><h2 className="text-xl font-bold">{reducing?'Your card balances are falling':'Your card balances need attention'}</h2><p className="mt-2 font-mono text-[34px] font-bold tabular-nums">£24,954 owed</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">{reducing?'Payments overtook new spending.':'New spending exceeded payments and one card is charging interest.'}</p><p className="mt-5 border-y border-slate-300 py-3 font-mono text-sm font-semibold dark:border-slate-700">£{opening.toLocaleString('en-GB')} opening + £{spend.toLocaleString('en-GB')} new spend − £{pay.toLocaleString('en-GB')} payments = £24,954 current debt</p></section>}
function Attention(){const[open,setOpen]=useState(false);return <section><div className="flex gap-3"><AlertTriangle aria-hidden="true" className="mt-1 shrink-0 text-amber-600"/><div><h2 className="text-base font-bold">Start with Halifax Clarity</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">£3,420 is charging 24.9% APR. An extra £120 this cycle would shorten the forecast by two months.</p><button type="button" onClick={()=>setOpen(!open)} aria-expanded={open} className="mt-3 min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white transition-colors hover:bg-indigo-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{open?'Hide repayment options':'See repayment options'}</button>{open&&<p className="mt-3 text-sm text-slate-600 dark:text-slate-400">An extra £120 shortens the forecast by two months; £240 shortens it by four.</p>}</div></div></section>}
function Drivers(){return <section><h2 className="text-base font-bold">What changed</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-400">Shopping, entertainment and groceries drove most of this cycle’s increase.</p><div className="mt-3 grid grid-cols-3 gap-3 border-y border-slate-300 py-3 text-sm dark:border-slate-700"><span><b>£560</b><br/>Shopping</span><span><b>£280</b><br/>Entertainment</span><span><b>£190</b><br/>Groceries</span></div></section>}
function Fleet(){const[open,setOpen]=useState<string|null>(null);return <section><h2 className="text-base font-bold">All card accounts</h2><div className="mt-3 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none">{cards.map(([name,balance,rate,note])=><div key={name} className="border-b border-slate-100 last:border-0 dark:border-slate-700"><button type="button" onClick={()=>setOpen(open===name?null:name)} aria-expanded={open===name} className="flex min-h-[70px] w-full items-center gap-3 px-4 text-left transition-colors hover:bg-slate-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo-500 dark:hover:bg-slate-700"><CreditCard aria-hidden="true" size={18} className="text-indigo-600"/><span className="min-w-0 flex-1"><b className="block text-sm">{name}</b><span className="text-xs text-slate-600 dark:text-slate-400">{rate}</span></span><b className="font-mono text-sm">{balance}</b><ChevronDown aria-hidden="true" size={16}/></button>{open===name&&<p className="border-t border-slate-100 px-4 py-3 text-sm text-slate-600 dark:border-slate-700 dark:text-slate-400">{note}. This account record contains its balance, rate and current projection.</p>}</div>)}</div></section>}
export default function G91CardsCanvasClient(){const p=useSearchParams(),v:V=p.get('variant')==='b'||p.get('variant')==='c'?p.get('variant')as V:'a',s:S=p.get('state')==='reducing'||p.get('state')==='empty'?p.get('state')as S:'growing',d=p.get('mode')==='dark';useEffect(()=>{document.documentElement.classList.toggle('dark',d)},[d]);const order=v==='a'?<><Attention/><Drivers/><Fleet/></>:v==='b'?<><Fleet/><Attention/><Drivers/></>:<><Drivers/><Attention/><Fleet/></>;return <div className={`${d?'dark':''} min-h-dvh bg-[#f0f2f7] pb-32 text-slate-900 dark:bg-[#0f172a] dark:text-slate-100`}><main className="mx-auto max-w-5xl px-4 py-8"><a href="/design" className="inline-flex min-h-11 items-center gap-1 text-sm text-slate-600 dark:text-slate-400"><ArrowLeft size={16}/>Back to design</a><header className="mt-4 border-b border-slate-300 pb-6 dark:border-slate-700"><h1 className="text-3xl font-bold">Cards</h1><p className="mt-2 text-sm text-slate-600 dark:text-slate-400">Which card needs attention?</p></header><div className="mt-8 space-y-9"><Position s={s}/>{s!=='empty'&&order}</div><p className="mt-10 text-xs text-slate-600 dark:text-slate-400">Illustrative figures only. A projection describes the current pace, not a promise.</p></main><Switch v={v} s={s} d={d}/></div>}
