import assert from "node:assert/strict";
import "./g186-hero-scale.test.mjs";
import { readFileSync } from "node:fs";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { fixture, incomeFor, STATES } from "../app/design/spend-hero/fixtures.ts";
import SpendPaceHero from "../components/SpendPaceHero.tsx";
import { spendHeroModel, spendHeroMoney } from "../lib/spendHero.ts";

const normal = fixture("normal");
assert.ok(normal);
assert.equal(normal.pills.spent, 3509);
assert.equal(normal.pills.income, 4800);
assert.equal(normal.moved_total, 500);
assert.equal(4010 - normal.pills.spent, 501, "usual pace and default Out reconcile");
assert.equal(normal.notables.reduce((sum, item) => sum + item.excess, 0), 111, "named category difference reconciles");
assert.equal((normal.pills.spent - 4010) - 111, -612, "residual is total minus named difference");
assert.equal(normal.notables.reduce((sum, item) => sum + item.spent, 0) + 2598 + normal.unresolved.total, normal.pills.spent, "Complete spending ledger reconciles to Out");
assert.equal(fixture("unplaced")?.unresolved.total, 125);
const unplaced = fixture("unplaced");
assert.ok(unplaced);
assert.equal(unplaced.notables.reduce((sum, item) => sum + item.spent, 0) + 2598 + unplaced.unresolved.total, unplaced.pills.spent, "Unplaced money remains in Out");
assert.equal(fixture("nobaseline")?.pace_series?.at(-1)?.usual, null, "No baseline cannot invent a pace comparison");
assert.equal(fixture("early")?.pace_series?.at(-1)?.usual, null, "Early period cannot invent a pace comparison");
assert.equal(fixture("empty")?.pace_series?.length, 0, "Empty state has no invented baseline");
assert.equal(fixture("nomoved")?.moved_total, 0);
assert.equal(fixture("loading"), null);
assert.equal(fixture("error"), null);
assert.ok(STATES.length >= 12);

const client = readFileSync(new URL("../app/design/spend-hero/SpendHeroClient.tsx", import.meta.url), "utf8");
const hero = readFileSync(new URL("../components/SpendPaceHero.tsx", import.meta.url), "utf8");
const page = readFileSync(new URL("../app/components/SpendPage.tsx", import.meta.url), "utf8");
assert.match(client, /import \{ SpendJourneySummary \} from "@\/components\/SpendHeader"/);
assert.match(client, /import SpendPaceHero from "@\/components\/SpendPaceHero"/);
assert.match(page, /import SpendPaceHero from "@\/components\/SpendPaceHero"/);
assert.match(page, /<SpendPaceHero/);
assert.doesNotMatch(page, /<SpendJourneySummary/);
assert.doesNotMatch(client, /function PaceHero\(/, "Approved A cannot retain a copy of the production markup");
assert.match(client, /import SpendJourneyNav/);
assert.match(client, /data-production-summary="true"/);
assert.match(hero, /data-g186-hero="b"/);
assert.match(client, /data-g186-hero="b"/);
assert.match(client, /data-g186-hero="c"/);
assert.match(client, /Transfers are shown separately/);
assert.match(client, /Usual pace is based on the median of up to three 30-day spending totals for each category before this pay period, adjusted for how far through the period you are\./);
assert.match(client, /Other differences/);
assert.match(client, /Balancing amount/);
assert.match(client, /Difference from usual pace/);
assert.match(client, /There is not enough comparable history for a pace comparison yet/);
assert.match(client, /g186-unplaced/);
assert.match(client, /scroll-mt-24/);
assert.doesNotMatch(client, /api\./, "Preview must not call a live API");
assert.doesNotMatch(client, /<aside\b/, "Auth-exempt previews must not use aside");
for (const { id } of STATES) {
  const value = fixture(id);
  if (!value) continue;
  assert.equal(Math.round((value.pills.income - value.pills.spent) * 100), Math.round(value.pills.net * 100));
  assert.equal(incomeFor(value).reduce((sum, row) => sum + row.amount, 0), value.pills.income);
  assert.equal(value.moved.reduce((sum, row) => sum + row.amount, 0), value.moved_total);
  assert.ok(value.pills.spent - value.notables.reduce((sum, row) => sum + row.spent, 0) - value.unresolved.total >= 0);
  for (const row of value.notables) {
    assert.equal(row.pace.spent, row.spent);
    assert.ok(Math.abs(row.spent - row.pace.usual_by_now - row.excess) < 0.001);
  }
}
assert.match(client, /onMovedTap: \(\) => jump\("g186-moved"\)/);
assert.match(client, /id="g186-moved"/);
assert.match(client, /shell\.style\.overflowX = "clip"/);
assert.match(page, /shell\.style\.overflowX = "clip"/);
assert.match(page, /shell\.style\.overflowX = previous/);
assert.match(page, /prefers-reduced-motion: reduce/);

const noOp = () => {};
const render = (verdict) => renderToStaticMarkup(React.createElement(SpendPaceHero, { verdict, incomeTxns: [], onTransactionClick: noOp, onOutTap: noOp, onMovedTap: noOp }));
const html = render(normal);
assert.equal((html.match(/class="glass-hero\b/g) ?? []).length, 1, "Only one hero instrument");
assert.match(html, /Below usual/);
assert.match(html, /£501/);
assert.doesNotMatch(html, /Two categories are running/, "Hero does not repeat the category-specific reading as an overall verdict");
assert.match(html, /Show income payments/);
assert.match(html, /Show money moved separately/);
assert.match(html, /How Out adds up/);
assert.match(html, /Moved separately is not included in Out/);
assert.equal(spendHeroModel(normal).other, 2598);
assert.equal(spendHeroModel(fixture("everything")).direction, "above");
assert.equal(spendHeroModel(fixture("nothing")).difference, -4010, "A genuine zero-spend baseline is not discarded");
assert.equal(spendHeroModel({ ...normal, state: "early" }).usual, null, "Early live payloads can have numeric pace points but must not claim reliability");
assert.equal(spendHeroModel({ ...normal, state: "nobaseline" }).usual, null);
assert.equal(spendHeroModel({ ...normal, pace_series: [...normal.pace_series, { day: 21, actual: 3509, usual: null }] }).usual, 4010, "Uses the existing latest non-null baseline");
assert.equal(spendHeroModel({ ...normal, period: { ...normal.period, days_elapsed: 7, days_left: 7 } }).totalDays, 14, "No hard-coded monthly period length");
assert.equal(spendHeroModel({ ...normal, moved_total: undefined }).moved, 500, "Older payloads use the existing moved rows");
assert.doesNotMatch(render(fixture("nomoved")), /Show money moved separately/, "No dead moved destination");
assert.match(render(fixture("closed")), /Completed pay period/);
assert.doesNotMatch(render(fixture("early")), /above usual pace|below usual pace/);
assert.equal(render(null), "", "No invented figures while loading");
assert.equal(spendHeroMoney(-0.001), "£0");
assert.equal(spendHeroMoney(-12.34), "−£12.34");
assert.equal(spendHeroMoney(1234567.89), "£1,234,567.89");
assert.equal(spendHeroModel({ ...normal, pills: { ...normal.pills, spent: 4010 + 1e-10 } }).direction, "level");

console.log("G186 Spend hero fixture and production-boundary checks passed");
