"use client";

import { FormEvent, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ArrowLeft, Check, ChevronRight, CircleAlert, LoaderCircle, Send } from "lucide-react";
import PennyMark from "@/components/PennyMark";

type Variant = "a" | "b" | "c";
type State = "ready" | "loading" | "error" | "allowance";
const states: State[] = ["ready", "loading", "error", "allowance"];
const messages: Record<Exclude<State, "ready">, [string, string]> = {
  loading: ["Checking your plan", "Penny is bringing together your latest balance, bills and planned moves."],
  error: ["Penny could not check that yet", "Your bank connection needs a refresh before Penny can give a reliable answer."],
  allowance: ["You have used all your Penny messages for this month", "Quick questions still work, and your allowance resets on 1 October."],
};
function Avatar() { return <div className="grid size-10 shrink-0 place-items-center rounded-2xl bg-gradient-to-br from-indigo-600 to-violet-600 text-white"><PennyMark size={20} /></div>; }

export default function G93PennyCanvasClient() {
  const params = useSearchParams(); const raw = params.get("variant"); const variant: Variant = raw === "b" || raw === "c" ? raw : "a"; const candidate = params.get("state") as State; const state: State = states.includes(candidate) ? candidate : "ready"; const dark = params.get("mode") === "dark";
  const [proposalOpen, setProposalOpen] = useState(false); const [confirmed, setConfirmed] = useState(false); const [question, setQuestion] = useState(""); const [localReply, setLocalReply] = useState("");
  useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]);
  const href = (next: Partial<{variant: Variant; state: State; mode: string}>) => `?variant=${next.variant ?? variant}&state=${next.state ?? state}&mode=${next.mode ?? (dark ? "dark" : "light")}`;
  const submit = (event: FormEvent) => { event.preventDefault(); if (question.trim()) setLocalReply(`Preview reply to “${question.trim()}”. No question was sent to Penny.`); };
  const proactive = variant === "c" && state === "ready";
  const [title, body] = state === "ready" ? ["Yes, £45 is safe this weekend", "After Saturday, you would still have £116 for the rest of this pay period."] : messages[state];
  return <main className="min-h-dvh bg-[#f0f2f7] text-slate-900 dark:bg-[#0f172a] dark:text-slate-100">
    <div className="mx-auto max-w-5xl px-4 pb-32 pt-6 sm:px-6"><header className="mb-8"><a href="/design" className="inline-flex min-h-11 items-center gap-1 text-sm font-semibold text-slate-600 dark:text-slate-400"><ArrowLeft size={16} />Design rounds</a><h1 className="mt-4 text-balance text-[30px] font-bold tracking-[-.04em]">What would you like to check?</h1><p className="mt-2 max-w-[65ch] text-sm leading-6 text-slate-600 dark:text-slate-400">Penny can look at this pay period, your next bills or a change you are considering.</p></header>
      <section aria-label="Penny conversation" className={variant === "b" ? "grid gap-8 lg:grid-cols-[minmax(0,1fr)_19rem]" : "mx-auto max-w-2xl"}><div className="space-y-6">
        <div className="flex items-start gap-3"><Avatar /><div><p className="text-sm font-bold">Penny</p><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-400">{proactive ? "I spotted a free weekend in your pay-period plan." : "I have your pay-period view open. What would you like to check?"}</p></div></div>
        {!proactive && state === "ready" && <div className="pl-[52px]"><p className="inline-block rounded-2xl bg-slate-200 px-4 py-3 text-sm dark:bg-slate-800">Can I spend £45 this weekend?</p></div>}
        {variant === "b" && state === "ready" && <div className="ml-[52px] rounded-2xl border border-slate-200 bg-white p-4 text-sm shadow-sm dark:border-slate-700 dark:bg-slate-800"><p className="font-bold">The facts Penny checked</p><dl className="mt-3 space-y-2 text-slate-600 dark:text-slate-400"><div className="flex justify-between gap-3"><dt>Balance refreshed</dt><dd>15 Sep, 09:40</dd></div><div className="flex justify-between gap-3"><dt>Bills before payday</dt><dd className="font-mono">£71</dd></div><div className="flex justify-between gap-3"><dt>Plan already set aside</dt><dd className="font-mono">£116</dd></div></dl></div>}
        <div className="flex items-start gap-3"><Avatar /><div><p className="text-sm font-bold">Penny</p><h2 className="mt-1 text-base font-bold">{proactive ? "Your weekend has room for a £45 treat" : title}</h2><p className="mt-1 max-w-[58ch] text-sm leading-6 text-slate-600 dark:text-slate-400">{proactive ? "Your bills are covered through 22 September. After £45 this weekend, £116 remains for the rest of the pay period." : body}</p>{state === "ready" && <p className="mt-3 text-xs leading-5 text-slate-500 dark:text-slate-400">Based on balances refreshed 15 September at 09:40 and scheduled bills. I am confident while those dates stay unchanged.</p>}{state === "loading" && <p role="status" className="mt-4 inline-flex items-center gap-2 text-sm text-slate-600 dark:text-slate-400"><LoaderCircle className="animate-spin text-indigo-600 motion-reduce:animate-none" size={16} />Checking your plan</p>}{state === "error" && <a href={href({state:"ready"})} className="mt-4 inline-flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-3 text-sm font-semibold dark:border-slate-700"><CircleAlert size={16} />Try again</a>}</div></div>
        {state === "ready" && <div className="ml-[52px] rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800"><p className="text-sm font-bold">{proactive ? "A useful follow-up" : "One proposal, ready to confirm"}</p><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-400">Set a quiet Sunday reminder to recheck what remains after the weekend. This does not alter your money or plan.</p>{proposalOpen ? <div className="mt-3 border-t border-slate-200 pt-3 dark:border-slate-700"><p className="text-sm font-semibold">Confirm the reminder?</p><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={() => { setConfirmed(true); setProposalOpen(false); }} className="min-h-11 rounded-xl bg-indigo-600 px-3 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500"><Check aria-hidden="true" size={16} className="mr-1 inline" />Confirm in preview</button><button type="button" onClick={() => setProposalOpen(false)} className="min-h-11 rounded-xl border border-slate-200 px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700">Not now</button></div></div> : <button type="button" onClick={() => setProposalOpen(true)} className="mt-3 min-h-11 rounded-xl bg-indigo-600 px-3 text-sm font-semibold text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">{confirmed ? "Confirmed in this preview" : "Review the reminder"}</button>}</div>}
        {state === "allowance" && <div className="ml-[52px]"><p className="text-sm font-semibold">Quick questions</p><button type="button" onClick={() => setLocalReply("Preview quick answer. No request was sent.")} className="mt-2 min-h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm font-semibold focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700 dark:bg-slate-800">What bills are next?</button></div>}
        {localReply && <p role="status" className="ml-[52px] border-y border-slate-200 py-3 text-sm text-slate-600 dark:border-slate-700 dark:text-slate-400">{localReply}</p>}
      </div>{variant === "b" && <aside className="border-t border-slate-200 pt-5 dark:border-slate-700 lg:border-l lg:border-t-0 lg:pl-7"><h2 className="text-base font-bold">Check the evidence</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">The dated balance, due bills and existing plan are visible because this answer depends on them.</p></aside>}</section>
      <form onSubmit={submit} className="mx-auto mt-10 flex max-w-2xl gap-2 border-t border-slate-200 pt-5 dark:border-slate-700"><label className="sr-only" htmlFor="ask">Ask Penny in this preview</label><input id="ask" name="penny-preview-question" autoComplete="off" value={question} onChange={event => setQuestion(event.target.value)} disabled={state === "loading" || state === "allowance"} placeholder="Try a local preview question…" className="min-h-11 min-w-0 flex-1 rounded-xl border border-slate-300 bg-white px-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 dark:border-slate-700 dark:bg-slate-800" /><button type="submit" aria-label="Show local preview reply" disabled={!question.trim() || state === "loading" || state === "allowance"} className="grid h-11 w-11 place-items-center rounded-xl bg-gradient-to-br from-indigo-600 to-violet-600 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 disabled:opacity-50"><Send aria-hidden="true" size={17} /></button></form>
    </div><nav aria-label="Preview controls" className="fixed bottom-3 left-1/2 z-20 flex max-w-[calc(100vw-24px)] -translate-x-1/2 gap-1 overflow-x-auto rounded-2xl bg-slate-950 p-1.5">{(["a","b","c"] as Variant[]).map(value => <a key={value} href={href({variant:value})} className="grid min-h-11 min-w-11 place-items-center rounded-xl px-2 text-xs font-bold text-white">{value.toUpperCase()}</a>)}{states.map(value => <a key={value} href={href({state:value})} className="inline-flex min-h-11 items-center rounded-xl px-2 text-xs font-semibold text-white">{value}</a>)}<a href={href({mode:dark?"light":"dark"})} className="inline-flex min-h-11 items-center rounded-xl px-2 text-xs text-white">{dark?"Light":"Dark"}</a></nav>
  </main>;
}
