"use client";

// G90 fixture-only design round. This intentionally does not import the live
// page because Upcoming fetches its own data; the fixtures preserve its runway,
// bill-risk and hidden-predictions branches without any API calls or writes.
import Link from "next/link";
import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, ChevronRight, EyeOff, Landmark, ReceiptText } from "lucide-react";
import { FIXTURES, fmtC, type PlanningFixture } from "../planning/fixtures";

type Variant = "a" | "b" | "c";
type State = "short" | "healthy" | "hidden";
const label: Record<Variant, string> = { a: "A · runway", b: "B · sequence", c: "C · briefing" };

function money(n: number) { return fmtC(n); }
function Runway({ data, compact = false }: { data: PlanningFixture; compact?: boolean }) {
  const short = data.runway < 0;
  return <section className={`glass-hero rounded-3xl p-5 shadow-sm ${compact ? "" : ""}`} aria-labelledby="runway-title">
    <h2 id="runway-title" className="text-xl font-bold tracking-tight text-slate-950 dark:text-slate-50">Projected at payday</h2>
    <p className="mt-1 max-w-xl text-sm text-slate-600 dark:text-slate-300">Your money between now and {data.paydayLabel}. This is a forecast, not a transfer.</p>
    <div className="mt-7 flex items-end justify-between gap-5 border-b border-slate-200 pb-5 dark:border-slate-700">
      <div><p className="text-[11px] font-semibold uppercase tracking-[.12em] text-slate-500">Projected at payday</p><p className={`mt-1 font-mono text-4xl font-bold tracking-tight tabular-nums ${short ? "text-rose-600 dark:text-rose-400" : "text-slate-950 dark:text-slate-50"}`}>{money(data.runway)}</p></div>
      <p className="pb-1 text-right text-xs text-slate-500 dark:text-slate-400">{data.daysToPayday} days left<br />{money(data.spendableNow)} available now</p>
    </div>
    {short ? <p className="mt-4 flex max-w-xl gap-2 text-sm text-slate-700 dark:text-slate-200"><AlertTriangle className="mt-0.5 shrink-0 text-rose-500" size={16} aria-hidden />Barclays could be short by <span className="font-mono font-semibold">£231.30</span> before payday. Review the two payments below.</p> : <p className="mt-4 max-w-xl text-sm text-slate-600 dark:text-slate-300">Bills and set-asides fit inside this pay period. Keep an eye on the dates, then carry on.</p>}
  </section>;
}
function Calculation({ data }: { data: PlanningFixture }) { return <details className="group mt-8 border-y border-slate-200 py-3 dark:border-slate-700"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between text-sm font-semibold text-slate-900 dark:text-slate-100">Full calculation <ChevronRight size={17} className="transition-transform group-open:rotate-90" /></summary><div className="grid grid-cols-[1fr_auto] gap-y-2 pt-3 text-sm text-slate-600 dark:text-slate-300"><span>Spendable now</span><span className="font-mono">{money(data.spendableNow)}</span><span>Bills due</span><span className="font-mono">−{money(data.billsTotal)}</span><span className="border-t border-slate-200 pt-2 font-semibold text-slate-900 dark:border-slate-700 dark:text-slate-100">Projected at payday</span><span className="border-t border-slate-200 pt-2 font-mono font-bold text-slate-900 dark:border-slate-700 dark:text-slate-100">{money(data.runway)}</span></div></details>; }
function Bills({ data }: { data: PlanningFixture }) { return <section className="mt-9" aria-labelledby="bills-title"><div className="mb-3 flex items-baseline justify-between"><h2 id="bills-title" className="text-base font-bold text-slate-950 dark:text-slate-50">Payments to watch</h2><span className="text-xs text-slate-500">This pay period</span></div><div className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800">{data.rows.filter(r => !r.isMovement).slice(0, 4).map((row, i) => <button type="button" key={row.id} className={`flex min-h-16 w-full items-center gap-3 px-4 text-left ${i ? "border-t border-slate-100 dark:border-slate-700" : ""}`}><span className={`grid h-8 w-8 place-items-center rounded-lg ${row.risk === "genuine" ? "bg-rose-100 text-rose-600 dark:bg-rose-950/50" : "bg-slate-100 text-slate-500 dark:bg-slate-700"}`}><ReceiptText size={15} /></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-900 dark:text-slate-100">{row.name}</span><span className="block text-xs text-slate-500">{row.dateLabel} · {row.bank}</span></span><span className={`font-mono text-sm font-semibold ${row.risk === "genuine" ? "text-rose-600 dark:text-rose-400" : "text-slate-900 dark:text-slate-100"}`}>−{money(row.amount)}</span></button>)}</div></section>; }
function Plans({ data }: { data: PlanningFixture }) { return <section className="mt-9" aria-labelledby="plans-title"><h2 id="plans-title" className="text-base font-bold text-slate-950 dark:text-slate-50">Set aside for later</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">These allocations already have a job, so they stay outside everyday spending.</p><div className="mt-3 space-y-2">{data.goals.map(g => <button type="button" key={g.name} className="flex min-h-16 w-full items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 text-left shadow-sm dark:border-slate-700 dark:bg-slate-800"><Landmark size={17} className="text-indigo-600 dark:text-indigo-400" /><span className="flex-1"><span className="block text-sm font-semibold text-slate-900 dark:text-slate-100">{g.name}</span><span className="text-xs text-slate-500">{money(g.perPeriod)} each pay period · {g.periodsLeft} left</span></span><ChevronRight size={17} className="text-slate-400" /></button>)}</div></section>; }
function CorrectiveAction({ data }: { data: PlanningFixture }) { const short=data.runway<0; return <section className="mt-9 border-t border-slate-200 pt-5 dark:border-slate-700"><h2 className="text-base font-bold text-slate-950 dark:text-white">One thing to do now</h2><p className="mt-1 text-sm leading-6 text-slate-600 dark:text-slate-300">{short ? "Check the two payments marked above before payday. That is the fastest way to close the projected gap." : "Nothing needs moving. Keep the dates in view and let the existing allocations do their job."}</p>{short && <Link href="/transactions" className="mt-4 inline-flex min-h-11 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white active:scale-95 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-indigo-500">Review payments</Link>}</section>; }
function Hidden() { return <main className="mx-auto min-h-screen max-w-2xl bg-[#f0f2f7] px-5 py-10 text-slate-900 dark:bg-slate-900 dark:text-slate-100 sm:px-9"><h1 className="text-xl font-bold">Upcoming</h1><div className="mt-10 max-w-xl"><EyeOff className="text-slate-400" size={25} /><h2 className="mt-4 text-2xl font-bold tracking-tight">2 predictions set aside</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">These individual predictions are quiet for now. Your runway, bills and other upcoming activity continue to appear as normal.</p><a href="/upcoming/dismissed" className="mt-6 inline-flex min-h-11 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500">Review set-aside predictions</a><p className="mt-4 text-xs text-slate-500">You can review or restore each prediction from the set-aside list.</p></div></main>; }
export default function UpcomingCanvasClient() { const p = useSearchParams(); const v = (["a","b","c"] as string[]).includes(p.get("variant") ?? "") ? p.get("variant") as Variant : "a"; const state = (["short","healthy","hidden"] as string[]).includes(p.get("state") ?? "") ? p.get("state")! as State : "short"; const dark = p.get("mode") === "dark"; useEffect(() => { document.documentElement.classList.toggle("dark", dark); }, [dark]); if(state === "hidden") return <><Hidden /><Controls v={v} state={state} dark={dark}/></>; const data=FIXTURES[state]; return <div className="min-h-screen bg-[#f0f2f7] pb-52 dark:bg-slate-900"><main className="mx-auto max-w-5xl px-5 py-8 sm:px-9"><header className="mb-7 max-w-2xl"><Link href="/design" className="inline-flex min-h-11 items-center text-sm font-semibold text-slate-600 dark:text-slate-300">Back to design</Link><h1 className="mt-3 text-3xl font-bold tracking-tight text-slate-950 dark:text-slate-50">Will I make it to payday?</h1><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Follow the forecast from today’s cash through every bill, set-aside and one-off before payday.</p></header><div className={v === "b" ? "grid gap-10 lg:grid-cols-[minmax(0,1fr)_280px]" : "max-w-2xl"}><div>{v === "c" && <p className="mb-5 text-sm font-semibold text-slate-600 dark:text-slate-300">{data.daysToPayday} days left · forecast first, then the dates behind it</p>}<Runway data={data}/><Calculation data={data}/><Bills data={data}/><Plans data={data}/><CorrectiveAction data={data}/></div>{v === "b" && <aside className="border-t border-slate-200 pt-6 dark:border-slate-700 lg:border-l lg:border-t-0 lg:pl-7 lg:pt-1"><p className="text-sm font-semibold">The forecast in order</p><ol className="mt-4 space-y-4 text-sm text-slate-600 dark:text-slate-300"><li>Runway and full calculation</li><li>Bills by date</li><li>Set-asides already spoken for</li><li>One practical correction</li></ol></aside>}</div></main><Controls v={v} state={state} dark={dark}/></div>; }
function Controls({v,state,dark}:{v:Variant;state:State;dark:boolean}) { const href=(variant:Variant,s:State,m:boolean)=>`?variant=${variant}&state=${s}&mode=${m?"dark":"light"}`; const base="inline-flex min-h-11 items-center justify-center rounded-xl px-3 py-2 hover:bg-white/10 focus-visible:ring-2 focus-visible:ring-white focus-visible:ring-offset-2 focus-visible:ring-offset-slate-900"; return <nav aria-label="Preview controls" className="fixed inset-x-0 bottom-3 z-50 mx-auto flex max-w-[96vw] flex-wrap justify-center gap-1 rounded-2xl bg-slate-900/95 p-1.5 text-[11px] shadow-xl">{(["a","b","c"] as Variant[]).map(x=><Link key={x} href={href(x,state,dark)} className={`${base} ${x===v?"bg-indigo-600 text-white":"text-slate-300"}`}>{label[x]}</Link>)}{(["short","healthy","hidden"] as State[]).map(x=><Link key={x} href={href(v,x,dark)} className={`${base} text-slate-300`}>{x}</Link>)}<Link href={href(v,state,!dark)} className={`${base} text-slate-300`}>{dark?"light":"dark"}</Link></nav>; }
