"use client";
import Link from "next/link";
import { useEffect } from "react";
import { useSearchParams } from "next/navigation";
import { AlertTriangle, ChevronRight, EyeOff, Landmark, ReceiptText } from "lucide-react";
import { FIXTURES, fmtC, type PlanningFixture } from "../planning/fixtures";
type V="a"|"b"|"c";type S="short"|"healthy"|"hidden";
const money=(n:number)=>fmtC(n);
function Runway({data}:{data:PlanningFixture}){const short=data.runway<0;return <section className="glass-hero rounded-3xl p-5 shadow-sm" aria-labelledby="runway"><h2 id="runway" className="text-xl font-bold">Projected at payday</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Your money between now and {data.paydayLabel}. This is a forecast, not a transfer.</p><p className={`mt-5 font-mono text-4xl font-bold tracking-tight ${short?'text-rose-600 dark:text-rose-400':'text-slate-950 dark:text-white'}`}>{money(data.runway)}</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{data.daysToPayday} days left · {money(data.spendableNow)} available now</p>{short?<p className="mt-4 flex gap-2 text-sm leading-6"><AlertTriangle className="mt-1 shrink-0 text-rose-500" size={16}/>Two payments could leave you short before payday.</p>:<p className="mt-4 text-sm leading-6 text-slate-600 dark:text-slate-300">Bills and set-asides fit inside this pay period.</p>}</section>}
function Calculation({data}:{data:PlanningFixture}){return <details className="border-y border-slate-200 py-3 dark:border-slate-700"><summary className="flex min-h-11 cursor-pointer list-none items-center justify-between text-sm font-semibold">Full calculation <ChevronRight size={17}/></summary><dl className="mt-3 grid grid-cols-[1fr_auto] gap-y-2 text-sm text-slate-600 dark:text-slate-300"><dt>Spendable now</dt><dd className="font-mono">{money(data.spendableNow)}</dd><dt>Bills due</dt><dd className="font-mono">−{money(data.billsTotal)}</dd><dt className="border-t pt-2 font-semibold">Projected at payday</dt><dd className="border-t pt-2 font-mono font-bold">{money(data.runway)}</dd></dl></details>}
function Bills({data}:{data:PlanningFixture}){return <section><div className="flex items-baseline justify-between"><h2 className="text-base font-bold">Payments by date</h2><span className="text-xs text-slate-500">This pay period</span></div><div className="mt-3 rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none">{data.rows.filter(r=>!r.isMovement).slice(0,4).map((r,i)=><div key={r.id} className={`flex min-h-16 items-center gap-3 px-4 ${i?'border-t border-slate-100 dark:border-slate-700':''}`}><span className={`grid h-8 w-8 place-items-center rounded-lg ${r.risk==='genuine'?'bg-rose-100 text-rose-600':'bg-slate-100 text-slate-500 dark:bg-slate-700'}`}><ReceiptText size={15}/></span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold">{r.name}</span><span className="block text-xs text-slate-500">{r.dateLabel} · {r.bank}</span></span><span className="font-mono text-sm font-semibold">−{money(r.amount)}</span></div>)}</div></section>}
function Allocations({data}:{data:PlanningFixture}){return <section><h2 className="text-base font-bold">Set aside for later</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">These allocations already have a job, so they sit outside everyday spending.</p><div className="mt-3 space-y-2">{data.goals.map(g=><div key={g.name} className="flex min-h-16 items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><Landmark size={17} className="text-indigo-600 dark:text-indigo-400"/><span><span className="block text-sm font-semibold">{g.name}</span><span className="text-xs text-slate-500">{money(g.perPeriod)} each pay period · {g.periodsLeft} left</span></span></div>)}</div></section>}
function Action({data}:{data:PlanningFixture}){const short=data.runway<0;return <section className="border-t border-slate-200 pt-5 dark:border-slate-700"><h2 className="text-base font-bold">One thing to do now</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{short?'Review the payments above before payday. That is the fastest way to close the projected gap.':'Nothing needs moving. Keep the dates in view and let the existing allocations do their job.'}</p>{short&&<Link href="/transactions" className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Review payments</Link>}</section>}
function Controls({v,s,d}:{v:V;s:S;d:boolean}){const h=(x:V,y:S,m:boolean)=>`?variant=${x}&state=${y}&mode=${m?'dark':'light'}`;return <nav aria-label="Preview controls" className="fixed inset-x-0 bottom-3 z-50 mx-auto flex max-w-[96vw] flex-wrap justify-center gap-1 rounded-2xl bg-slate-900/95 p-1.5 text-xs shadow-xl">{(['a','b','c']as V[]).map(x=><Link key={x} href={h(x,s,d)} className={`inline-flex min-h-11 items-center rounded-xl px-3 ${x===v?'bg-indigo-600 text-white':'text-slate-200'}`}>{x.toUpperCase()}</Link>)}{(['short','healthy','hidden']as S[]).map(x=><Link key={x} href={h(v,x,d)} className="inline-flex min-h-11 items-center rounded-xl px-3 text-slate-200">{x}</Link>)}<Link href={h(v,s,!d)} className="inline-flex min-h-11 items-center rounded-xl px-3 text-slate-200">{d?'light':'dark'}</Link></nav>}
export default function UpcomingCanvasClient(){const p=useSearchParams();const v=(['a','b','c']as string[]).includes(p.get('variant')??'')?p.get('variant')as V:'a';const s=(['short','healthy','hidden']as string[]).includes(p.get('state')??'')?p.get('state')as S:'short';const d=p.get('mode')==='dark';useEffect(()=>{document.documentElement.classList.toggle('dark',d)},[d]);if(s==='hidden')return <main className="min-h-screen bg-[#f0f2f7] px-5 py-10 dark:bg-slate-900"><EyeOff className="text-slate-400"/><h1 className="mt-4 text-2xl font-bold">2 predictions set aside</h1><p className="mt-2 max-w-lg text-sm leading-6 text-slate-600 dark:text-slate-300">Your runway, bills and other upcoming activity continue to appear as normal.</p><Link href="/upcoming/dismissed" className="mt-5 inline-flex min-h-11 items-center rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white">Review set-aside predictions</Link><Controls v={v} s={s} d={d}/></main>;const data=FIXTURES[s];const body=v==='a'?<><Runway data={data}/><Calculation data={data}/><Bills data={data}/><Allocations data={data}/><Action data={data}/></>:v==='b'?<div className="grid grid-cols-1 gap-8 lg:grid-cols-[minmax(0,1fr)_300px]"><div className="space-y-8"><Bills data={data}/><Allocations data={data}/><Action data={data}/></div><aside className="order-first lg:order-none lg:sticky lg:top-6"><Runway data={data}/><div className="mt-6"><Calculation data={data}/></div></aside></div>:data.runway<0?<><Action data={data}/><Runway data={data}/><Bills data={data}/><Calculation data={data}/><Allocations data={data}/></>:<><Runway data={data}/><Action data={data}/><Allocations data={data}/><Bills data={data}/><Calculation data={data}/></>;return <div className="min-h-screen bg-[#f0f2f7] pb-32 dark:bg-slate-900"><main className="mx-auto max-w-5xl space-y-8 px-5 py-8 sm:px-9"><Link href="/design" className="inline-flex min-h-11 items-center text-sm text-slate-600 dark:text-slate-300">Back to design</Link><header><h1 className="text-3xl font-bold tracking-tight">Will I make it to payday?</h1><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">Follow the forecast from today’s cash through every bill, set-aside and one-off before payday.</p></header>{body}</main><Controls v={v} s={s} d={d}/></div>}
