#!/usr/bin/env python3
"""Generate the Python and TypeScript copies of the sign-in hand-off template.

Single source: shared/signin-handoff/template.html (plain HTML with {{slot}}
placeholders). The backend deploys from backend/ alone and the frontend from
frontend/, so neither can read the shared/ file at runtime; each gets a
generated module instead. Edit the .html, run this script, commit all three.
`--check` exits 1 if either generated file is stale.
"""
import hashlib
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "shared" / "signin-handoff" / "template.html"
PY_OUT = ROOT / "backend" / "app" / "core" / "signin_handoff_template.py"
TS_OUT = ROOT / "shared" / "src" / "signinHandoffTemplate.ts"
NOTE = "GENERATED by scripts/gen_signin_handoff.py from shared/signin-handoff/template.html. Do not edit."


def build() -> dict[Path, str]:
    html = SRC.read_text(encoding="utf-8")
    sha = hashlib.sha256(html.encode("utf-8")).hexdigest()
    py = f'# {NOTE}\nTEMPLATE_SHA256 = "{sha}"\nTEMPLATE = {html!r}\n'
    ts = (
        f"// {NOTE}\n"
        f'export const SIGNIN_HANDOFF_TEMPLATE_SHA256 = "{sha}";\n'
        f"export const SIGNIN_HANDOFF_TEMPLATE: string = {json.dumps(html)};\n"
    )
    return {PY_OUT: py, TS_OUT: ts}


def main() -> int:
    outs = build()
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, t in outs.items() if not p.exists() or p.read_text() != t]
        if stale:
            print("stale generated template files (run scripts/gen_signin_handoff.py):", *stale)
            return 1
        print("signin handoff template copies are in sync")
        return 0
    for p, t in outs.items():
        p.write_text(t, encoding="utf-8")
        print("wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
