import { ArrowRightLeft, Landmark } from "lucide-react";
import type { UpcomingRowModel } from "@/components/upcoming/UpcomingRow";

// G176 uses invented, internally consistent fixtures. The route is public and
// auth-exempt, so no live account names, balances or payment descriptions
// belong here. The deliberately long names exercise the exact phone-width
// failure the round is intended to solve.
export const LATE_MOVE_ROWS: UpcomingRowModel[] = [
  {
    rowKey: "bill-household-bills-transfer-2026-09-29",
    type: "bill",
    name: "Household bills transfer to our Monzo joint account",
    amount: 820,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: 1284 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
  {
    rowKey: "bill-mortgage-reserve-2026-09-29",
    type: "bill",
    name: "Mortgage reserve to NatWest Home Account",
    amount: 605,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: 679 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
  {
    rowKey: "bill-savings-move-2026-09-29",
    type: "bill",
    name: "Monthly savings move to Rainy Day Saver",
    amount: 350,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: 329 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
  {
    rowKey: "bill-spending-transfer-2026-09-29",
    type: "bill",
    name: "Everyday spending transfer to Chase Current Account",
    amount: 180,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: 149 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
  {
    rowKey: "bill-annual-costs-transfer-2026-09-29",
    type: "bill",
    name: "Annual costs move to First Direct Regular Saver",
    amount: 120,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: 29 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
  {
    rowKey: "bill-travel-money-transfer-2026-09-29",
    type: "bill",
    name: "Travel money transfer to Revolut holiday balance",
    amount: 75,
    expectedDate: "2026-09-29",
    originalDate: "2026-09-25",
    category: "Transfer",
    accountLabel: "Premier Current Account",
    accountBalance: 410,
    isMovement: true,
    pending: true,
    daysPastDue: 4,
    movementCalm: true,
    unfundedMovement: true,
    after: { kind: "balance", value: -46 },
    categoryColour: "#94a3b8",
    CategoryIcon: ArrowRightLeft,
  },
];

export const ORDINARY_ROW: UpcomingRowModel = {
  rowKey: "bill-council-tax-2026-09-29",
  type: "bill",
  name: "Council Tax to Brighton and Hove City Council",
  amount: 154.54,
  expectedDate: "2026-09-29",
  category: "Bills",
  accountLabel: "Everyday Current Account",
  after: { kind: "balance", value: 1949 },
  categoryColour: "#fb7185",
  CategoryIcon: Landmark,
};

export const NEXT_DAY_ROW: UpcomingRowModel = {
  rowKey: "bill-broadband-2026-09-30",
  type: "bill",
  name: "Broadband",
  amount: 34,
  expectedDate: "2026-09-30",
  category: "Bills",
  accountLabel: "Everyday Current Account",
  after: { kind: "balance", value: 1915 },
  categoryColour: "#fb7185",
  CategoryIcon: Landmark,
};
