"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ChevronDown, ChevronLeft, ChevronRight, Info } from "lucide-react";
type V = "a"|"b"|"c"; type S = "steady"|"changed"|"thin"|"overspent";
type Row={name:string; amount:string; detail:string; colour:string};
const standard: Row[]=[{name:"Fixed",amount:"£1,120",detail:"Bills and commitments",colour:"bg-slate-500"},{name:"Moved",amount:"£640",detail:"Savings and investing",colour:"bg-emerald-500"},{name:"Free",amount:"£510",detail:"Everyday spending",colour:"bg-sky-500"},{name:"Left",amount:"£280",detail:"Still in this pay period",colour:"bg-slate-300"}];
function rows(s:S){return s==="thin"?[standard[0],standard[2]]:s==="overspent"?[standard[0],standard[1],{name:"Free",amount:"£790",detail:"Everyday spending",colour:"bg-sky-500"},{name:"Beyond take-home",amount:"£180",detail:"Spent after take-home was assigned",colour:"bg-amber-400"}]:standard}
function Controls({v,s,d}:{v:V;s:S;d:boolean}){const h=(x:V,y:S,m:boolean)=>`?variant=${x}&state=${y}&mode=${m?"dark":"light"}`;return <nav aria-label="Preview controls" className="fixed inset-x-0 bottom-3 z-50 mx-auto flex max-w-[96vw] flex-wrap justify-center gap-1 rounded-2xl bg-slate-900/95 p-1.5 text-xs shadow-xl">{(["a","b","c"]as V[]).map(x=><Link key={x} href={h(x,s,d)} className={`inline-flex min-h-11 items-center rounded-xl px-3 ${x===v?"bg-indigo-600 text-white":"text-slate-200"}`}>{x.toUpperCase()}</Link>)}{(["steady","changed","thin","overspent"]as S[]).map(x=><Link key={x} href={h(v,x,d)} className="inline-flex min-h-11 items-center rounded-xl px-3 text-slate-200">{x}</Link>)}<Link href={h(v,s,!d)} className="inline-flex min-h-11 items-center rounded-xl px-3 text-slate-200">{d?"light":"dark"}</Link></nav>}
function Instrument({s}:{s:S}){const [open,setOpen]=useState(false);const data=rows(s);const widths=s==="thin"?[69,31]:s==="overspent"?[41,23,29,7]:[44,25,20,11];return <section className="glass-hero rounded-3xl p-5 shadow-sm" aria-labelledby="shape-title"><div className="flex items-center justify-between"><span className="grid min-h-11 min-w-11 place-items-center text-slate-400"><ChevronLeft size={18}/></span><span className="inline-flex min-h-11 items-center text-sm font-semibold">Last pay period <ChevronDown className="ml-1" size={15}/></span><span className="grid min-h-11 min-w-11 place-items-center text-slate-400"><ChevronRight size={18}/></span></div><h2 id="shape-title" className="mt-5 text-2xl font-bold tracking-tight">How this pay period was split</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">A reconciled picture of where your take-home went.</p><div className="mt-6 flex h-8 overflow-hidden rounded-full bg-slate-200 dark:bg-slate-700">{data.map((r,i)=><span key={r.name} className={r.colour} style={{width:`${widths[i]}%`}} />)}</div><div className="mt-5 space-y-1">{data.map(r=><Link key={r.name} href="/transactions" className="flex min-h-12 items-center gap-3 border-b border-slate-200 py-2 text-sm dark:border-slate-700"><span className={`h-2.5 w-2.5 rounded-full ${r.colour}`}/><span className="flex-1 font-semibold">{r.name}<span className="block text-xs font-normal text-slate-500">{r.detail}</span></span><span className="font-mono font-semibold">{r.amount}</span><ChevronRight size={15} className="text-slate-400"/></Link>)}</div>{s==="changed"&&<p className="mt-4 flex gap-2 text-sm"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-amber-500"/>Free spending is £120 above your usual shape.</p>}{s==="overspent"&&<p className="mt-4 flex gap-2 text-sm"><span className="mt-2 h-1.5 w-1.5 rounded-full bg-amber-500"/>Beyond take-home is spending after your pay had already been assigned.</p>}<button type="button" onClick={()=>setOpen(!open)} className="mt-5 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-600 dark:text-indigo-400"><Info size={16}/>How this is worked out</button>{open&&<p className="mt-2 border-t border-slate-200 pt-3 text-sm leading-6 text-slate-600 dark:border-slate-700 dark:text-slate-300">Fixed covers commitments. Moved covers savings and investing. Free covers everyday spending. Left is what remains. Beyond take-home only appears when spending exceeded take-home after those jobs.</p>}</section>}
function Reading({s}:{s:S}){const text=s==="thin"?"There is not enough history yet to compare this period. Missing jobs fill in when the pay period settles.":s==="overspent"?"Fixed and moved money stayed protected. The next useful check is spending after take-home.":s==="changed"?"Savings and investing still moved first. The free slice is the only part that changed.":"Savings and investing moved before free spending, leaving room at the end of the period.";return <section className="border-t border-slate-200 pt-5 dark:border-slate-700"><h2 className="text-base font-bold">What is working</h2><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">{text}</p></section>}
function Reference(){return <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm dark:border-slate-700 dark:bg-slate-800 dark:shadow-none"><h2 className="text-base font-bold">Reference shapes</h2><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">Compare with your usual pattern when this one needs explaining.</p><Link href="/mirror" className="mt-3 inline-flex min-h-11 items-center text-sm font-semibold text-indigo-600 dark:text-indigo-400">View your usual shape</Link></section>}
export default function MoneyShapeCanvasClient(){const p=useSearchParams();const v=(["a","b","c"]as string[]).includes(p.get("variant")??"")?p.get("variant")as V:"a";const s=(["steady","changed","thin","overspent"]as string[]).includes(p.get("state")??"")?p.get("state")as S:"steady";const d=p.get("mode")==="dark";useEffect(()=>document.documentElement.classList.toggle("dark",d),[d]);const story=v==="a"?<><Instrument s={s}/><Reading s={s}/><Reference/></>:v==="b"?<><Reference/><Instrument s={s}/><Reading s={s}/></>:<><Reading s={s}/><Instrument s={s}/><Link href="/spend" className="inline-flex min-h-11 items-center text-sm font-semibold text-indigo-600 dark:text-indigo-400">Return to Spend <ChevronRight size={16}/></Link></>;return <div className="min-h-screen bg-[#f0f2f7] pb-32 dark:bg-slate-900"><main className="mx-auto max-w-3xl space-y-8 px-5 py-8 sm:px-9"><Link href="/spend" className="inline-flex min-h-11 items-center gap-1 text-sm text-slate-600 dark:text-slate-300"><ChevronLeft size={16}/>Back to Spend</Link><header><h1 className="text-3xl font-bold tracking-tight">Where did this pay period go, and is that shape working?</h1><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-300">The shape is the answer. Everything after it helps decide whether to keep it.</p></header>{story}</main><Controls v={v} s={s} d={d}/></div>}
