"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { ChevronDown, ChevronRight, Filter, Search, SlidersHorizontal, Sparkles } from "lucide-react";

type Variant = "a" | "b" | "c"; type State = "populated" | "long" | "loading" | "empty" | "error";
const transactions = [
  ["Today", "Pret A Manger", "Eating out", "−£8.45"], ["Today", "Tesco", "Groceries", "−£42.18"], ["Yesterday", "TfL Travel", "Transport", "−£3.20"], ["Yesterday", "Spotify", "Subscriptions", "−£11.99"], ["Mon 7 Sept", "Salary", "Income", "+£2,950.00"], ["Mon 7 Sept", "Octopus Energy", "Bills", "−£74.00"],
];
const colour: Record<string,string> = { "Eating out":"#fb923c", Groceries:"#34d399", Transport:"#60a5fa", Subscriptions:"#22d3ee", Income:"#4ade80", Bills:"#fb7185" };
function Controls({ v,s,dark}:{v:Variant;s:State;dark:boolean}) { const h=(x:Variant,y:State,m:boolean)=>`?variant=${x}&state=${y}&mode=${m?"dark":"light"}`; const base="inline-flex min-h-11 shrink-0 items-center justify-center rounded-xl px-2.5 py-2 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white"; return <nav aria-label="Preview controls" className="fixed inset-x-0 bottom-3 z-50 mx-auto flex max-w-[calc(100vw-16px)] flex-nowrap gap-1 overflow-x-auto rounded-2xl bg-slate-900/95 p-1.5 text-[11px] shadow-xl">{(["a","b","c"] as Variant[]).map(x=><Link key={x} href={h(x,s,dark)} className={`${base} ${x===v?"bg-indigo-600 text-white":"text-slate-200 hover:bg-slate-800"}`}>{x.toUpperCase()}</Link>)}{(["populated","long","loading","empty","error"] as State[]).map(x=><Link key={x} href={h(v,x,dark)} className={`${base} text-slate-200 hover:bg-slate-800`}>{x}</Link>)}<Link href={h(v,s,!dark)} className={`${base} text-slate-200 hover:bg-slate-800`}>{dark?"light":"dark"}</Link></nav> }
function SearchBox() { return <label className="mt-5 flex min-h-12 items-center gap-2 rounded-xl border border-slate-200 bg-white px-3 shadow-sm focus-within:ring-2 focus-within:ring-indigo-500 dark:border-slate-700 dark:bg-slate-800"><Search size={17} className="text-slate-400" aria-hidden="true"/><input aria-label="Search transactions" name="transaction-search" autoComplete="off" placeholder="Search payments, shops or amounts…" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-slate-400 dark:text-slate-100"/><button type="button" aria-label="Open filters" className="grid min-h-11 min-w-11 place-items-center rounded-lg text-slate-500 hover:bg-slate-100 focus-visible:ring-2 focus-visible:ring-indigo-500 dark:hover:bg-slate-700"><SlidersHorizontal size={17}/></button></label> }
function Summary({v}:{v:Variant}) { const text = v === "a" ? "6 payments found across all your accounts." : v === "b" ? "Showing the newest activity first, with filters ready when you need them." : "Every payment is here. Open a row to check or teach its category."; return <p className="mt-5 max-w-2xl text-sm leading-6 text-slate-600 dark:text-slate-300">{text}</p> }
function Group({ rows, day, expanded }: { rows: typeof transactions; day:string; expanded:boolean }) { const [open,setOpen]=useState(expanded); return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-700 dark:bg-slate-800"><h2 className="px-4 pt-4 text-sm font-bold text-slate-950 dark:text-slate-50">{day}</h2>{rows.map((r,i)=><button type="button" key={`${r[1]}${i}`} onClick={()=>setOpen(!open)} className={`flex min-h-[68px] w-full items-center gap-3 px-4 text-left hover:bg-slate-50 focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-indigo-500 dark:hover:bg-slate-700/40 ${i?"border-t border-slate-100 dark:border-slate-700":""}`}><span className="h-8 w-1 rounded-full" style={{background:colour[r[2]]}} aria-hidden="true"/><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold text-slate-900 dark:text-slate-100">{r[1]}</span><span className="block truncate text-xs text-slate-500 dark:text-slate-300">{r[2]}</span></span><span className="font-mono text-sm font-semibold tabular-nums text-slate-900 dark:text-slate-100">{r[3]}</span><ChevronRight size={16} className={`shrink-0 text-slate-400 dark:text-slate-300 transition-transform ${open?"rotate-90":""}`} /></button>)}{open && <div className="border-t border-slate-100 px-4 py-3 text-xs leading-5 text-slate-600 dark:border-slate-700 dark:text-slate-300"><Sparkles size={14} className="mr-1 inline text-indigo-500" aria-hidden="true"/>Teaching this category helps future payments land in the right place.</div>}</section> }
function StateBody({state,v}:{state:State;v:Variant}) { if(state==="loading") return <div className="mt-8 space-y-3" aria-label="Loading transactions"><div className="h-24 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-700"/><div className="h-40 animate-pulse rounded-2xl bg-slate-200 dark:bg-slate-700"/></div>; if(state==="empty") return <section className="mt-10 max-w-xl border-y border-slate-200 py-8 dark:border-slate-700"><h2 className="text-lg font-bold">No payments match this search</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Try a different shop, amount or filter. Your transaction history is still safe.</p><button className="mt-4 min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500">Clear search & filters</button></section>; if(state==="error") return <section className="mt-10 max-w-xl border-y border-slate-200 py-8 dark:border-slate-700"><h2 className="text-lg font-bold">Transactions could not load</h2><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Check your connection, then try again. No changes have been made.</p><button className="mt-4 min-h-11 rounded-xl bg-indigo-600 px-4 text-sm font-semibold text-white hover:bg-indigo-700 focus-visible:ring-2 focus-visible:ring-indigo-500">Try again</button></section>; const more=state==="long"?[...transactions,...transactions,...transactions]:transactions; const days=[...new Set(more.map(x=>x[0]))]; return <div className={`mt-7 gap-4 ${v==="b"?"grid lg:grid-cols-2":"space-y-4"}`}>{days.map(day=><Group key={day} day={day} rows={more.filter(x=>x[0]===day)} expanded={v==="c"}/>)}</div> }
export default function TransactionsCanvasClient(){const p=useSearchParams(); const v=(["a","b","c"] as string[]).includes(p.get("variant")??"")?p.get("variant") as Variant:"a"; const state=(["populated","long","loading","empty","error"] as string[]).includes(p.get("state")??"")?p.get("state") as State:"populated"; const dark=p.get("mode")==="dark"; useEffect(()=>{document.documentElement.classList.toggle("dark",dark)},[dark]); return <div className="min-h-screen bg-[#f0f2f7] pb-32 dark:bg-slate-900"><main id="main-content" className="mx-auto max-w-5xl px-5 py-8 sm:px-9"><a href="#transactions" className="sr-only focus:not-sr-only focus:absolute focus:rounded focus:bg-white focus:p-2">Skip to transactions</a><header className={v==="b"?"lg:grid lg:grid-cols-[1fr_300px] lg:gap-10":"max-w-2xl"}><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-slate-50">Transactions</h1><SearchBox/><Summary v={v}/></div>{v==="b"&&<aside className="mt-6 border-t border-slate-200 pt-5 dark:border-slate-700 lg:mt-0 lg:border-l lg:border-t-0 lg:pl-7"><p className="text-sm font-semibold">All history</p><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">6 payments, 4 categories, 3 accounts.</p><button className="mt-4 flex min-h-11 items-center gap-2 text-sm font-semibold text-indigo-600 hover:underline focus-visible:ring-2 focus-visible:ring-indigo-500 dark:text-indigo-400"><Filter size={16}/>Refine results</button></aside>}</header><div id="transactions"><StateBody state={state} v={v}/></div></main><Controls v={v} s={state} dark={dark}/></div>}
